### ISSUE TITLE
NPE in ApiBaseline on adding new JVM

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1042]
Using 4.31.0.I20240104-1800, I've added new JRE in Java settings and right after doing that got error below in the log.

```
org.eclipse.core.jobs
Error
Fri Jan 05 09:33:17 CET 2024
An internal error occurred during: "Performing API Analysis".

java.lang.NullPointerException: Cannot invoke "java.util.HashSet.add(Object)" because "this.fSystemPackageNames" is null
	at org.eclipse.pde.api.tools.internal.model.ApiBaseline.isSystemPackage(ApiBaseline.java:659)
	at org.eclipse.pde.api.tools.internal.model.ApiBaseline.resolvePackage(ApiBaseline.java:555)
	at org.eclipse.pde.api.tools.internal.model.ApiType.resolveSuperType(ApiType.java:286)
	at org.eclipse.pde.api.tools.internal.model.ApiType.getSuperInterfaces(ApiType.java:254)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.collectAllInterfaces(ClassFileComparator.java:906)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.getInterfacesSet(ClassFileComparator.java:2048)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.checkSuperInterfaces(ClassFileComparator.java:298)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.getDelta(ClassFileComparator.java:1193)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator$2.visit(ApiComparator.java:751)
	at org.eclipse.pde.api.tools.internal.model.ArchiveApiTypeContainer.accept(ArchiveApiTypeContainer.java:189)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.internalCompare(ApiComparator.java:635)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.compare(ApiComparator.java:284)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.compare(ApiComparator.java:307)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.checkCompatibility(BaseApiAnalyzer.java:1457)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.analyzeComponent(BaseApiAnalyzer.java:268)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.buildAll(ApiAnalysisBuilder.java:912)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.work(ApiAnalysisBuilder.java:407)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder$ApiAnalysisJob.run(ApiAnalysisBuilder.java:553)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The problem is that `ApiBaseline.initialize()` is not only called from constructor but also from `resolveSystemLibrary()` that can be triggered by `rebindVM()`. Ideally the whole class should be refactored to avoid that it can be used while it is internally re-initializes all the data, but I have no time to run such refactoring. 

I will propose a PR that would not fully fix the issue, but reduce its probability.

**Comment by laeubi** [comment]
In fact ApiBaseline, and its components should become unmodifiable (e.g. records, final classes) that never change their state. This would prevent a lot of concurrency issues we seen with API tools.
