### ISSUE TITLE
Deadlock in API tooling after removing projects from workspace

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1088]
Using build I20240128-1800. After updating workspace on latest master (where e4 projects were removed) API tools caused a deadlock - after pull, while build was running, I've selected one of the "removed" e4 tools projects and that immediately freeze the UI.

Looks like the deadlock happens because the **disposed** API component (from removed project) is used in two threads - one that runs API checks in a Job and another one that disposes the same component as a result of project removal.

The synchronization introduced in 1ac36e3b3ab471423454932740e7ca1466fd6415 is one part of the problem.
Another one is the synchronization on `org.eclipse.pde.api.tools.internal.model.Component.fApiDescription` field in `Component.dispose()`. In general, all synchronization in PDE is pretty inconsistent and only works by occasion.

I believe the **main issue** is however that `WorkspaceDeltaProcessor.processJavaElementDeltas()` calls  to `ApiBaselineManager.disposeWorkspaceBaseline()` **while** API analysis is running.
There was an attempt to mitigate that by cancelling ApiAnalysisJob jobs in `ApiBaselineManager.disposeWorkspaceBaseline()` but this is obviously not enough.

I think we should check if we can run this baseline disposal as a job and make it conflicting with API analysis jobs, so they can't run in parallel.

I will try to provide a PR.

[Full thread dump](https://github.com/eclipse-pde/eclipse.pde/files/14081441/pde_api_tools_deadlock.txt)

Here is the relevant part:

```
Found one Java-level deadlock:
=============================
"main":
  waiting to lock monitor 0x00007ffdb8140890 (object 0x00000004061b8e48, a java.lang.Object),
  which is held by "Worker-137: Updating API analysis markers on org.eclipse.e4.ui.workbench.renderers.swt"

"Worker-137: Updating API analysis markers on org.eclipse.e4.ui.workbench.renderers.swt":
  waiting to lock monitor 0x00007ffd181f31d0 (object 0x00000004a8f5ad58, a org.eclipse.pde.api.tools.internal.model.ProjectComponent),
  which is held by "Worker-300: Performing API Analysis"

"Worker-300: Performing API Analysis":
  waiting to lock monitor 0x00007ffdb8140890 (object 0x00000004061b8e48, a java.lang.Object),
  which is held by "Worker-137: Updating API analysis markers on org.eclipse.e4.ui.workbench.renderers.swt"

Java stack information for the threads listed above:
===================================================
"main":
        at org.eclipse.pde.internal.core.PluginModelManager.findModel(PluginModelManager.java:1068)
        - waiting to lock <0x00000004061b8e48> (a java.lang.Object)
        at org.eclipse.pde.internal.core.DynamicPluginProjectReferences.getDependentProjects(DynamicPluginProjectReferences.java:47)
        at org.eclipse.core.internal.resources.ProjectDescription.computeDynamicReferencesForProject(ProjectDescription.java:949)
        at org.eclipse.core.internal.resources.ProjectDescription.getAllBuildConfigReferences(ProjectDescription.java:265)
        at org.eclipse.core.internal.resources.ProjectDescription.getAllReferences(ProjectDescription.java:222)
        at org.eclipse.core.internal.resources.Project.getReferencedProjects(Project.java:502)
        at org.eclipse.ui.actions.CloseUnrelatedProjectsAction.buildConnectedComponents(CloseUnrelatedProjectsAction.java:83)
        at org.eclipse.ui.actions.CloseUnrelatedProjectsAction.computeRelated(CloseUnrelatedProjectsAction.java:206)
        at org.eclipse.ui.actions.CloseUnrelatedProjectsAction.getSelectedResources(CloseUnrelatedProjectsAction.java:226)
        at org.eclipse.ui.actions.SelectionListenerAction.selectionIsOfType(SelectionListenerAction.java:242)
        at org.eclipse.ui.actions.CloseResourceAction.updateSelection(CloseResourceAction.java:231)
        at org.eclipse.ui.actions.BaseSelectionListenerAction.selectionChanged(BaseSelectionListenerAction.java:128)
        at org.eclipse.jdt.ui.actions.ProjectActionGroup.performSelectionChanged(ProjectActionGroup.java:136)
        at org.eclipse.jdt.ui.actions.ProjectActionGroup.lambda$0(ProjectActionGroup.java:115)
        at org.eclipse.jdt.ui.actions.ProjectActionGroup$$Lambda/0x00007fff6866c8c8.selectionChanged(Unknown Source)
        at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.ui.internal.JFaceUtil$$Lambda/0x00007fff681dec40.run(Unknown Source)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
        at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
        at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2132)
        at org.eclipse.jface.viewers.ColumnViewer.updateSelection(ColumnViewer.java:1055)
        at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1170)
        at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1199)
        at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:262)
        at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:420)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
        at org.eclipse.ui.internal.Workbench$$Lambda/0x00007fff6823e758.run(Unknown Source)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
        at java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.base@21.0.1/DirectMethodHandle$Holder)
        at java.lang.invoke.LambdaForm$MH/0x00007fff68007800.invoke(java.base@21.0.1/LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/0x00007fff68007c00.invokeExact_MT(java.base@21.0.1/LambdaForm$MH)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.1/DirectMethodHandleAccessor.java:155)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.1/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.1/Method.java:580)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
"Worker-137: Updating API analysis markers on org.eclipse.e4.ui.workbench.renderers.swt":
        at org.eclipse.pde.api.tools.internal.model.Component.dispose(Component.java:88)
        - waiting to lock <0x00000004a8f5ad58> (a org.eclipse.pde.api.tools.internal.model.ProjectComponent)
        at org.eclipse.pde.api.tools.internal.model.BundleComponent.dispose(BundleComponent.java:185)
        at org.eclipse.pde.api.tools.internal.model.ProjectComponent.dispose(ProjectComponent.java:178)
        at org.eclipse.pde.api.tools.internal.model.ApiBaseline.doDispose(ApiBaseline.java:834)
        at org.eclipse.pde.api.tools.internal.model.WorkspaceBaseline.dispose(WorkspaceBaseline.java:56)
        at org.eclipse.pde.api.tools.internal.ApiBaselineManager.disposeWorkspaceBaseline(ApiBaselineManager.java:649)
        at org.eclipse.pde.api.tools.internal.WorkspaceDeltaProcessor.processJavaElementDeltas(WorkspaceDeltaProcessor.java:80)
        at org.eclipse.pde.api.tools.internal.WorkspaceDeltaProcessor.elementChanged(WorkspaceDeltaProcessor.java:51)
        at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1761)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1749)
        at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1582)
        at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1558)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:783)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:808)
        at org.eclipse.jdt.core.JavaCore.setClasspathContainer(JavaCore.java:6213)
        at org.eclipse.pde.internal.core.PluginModelManager.updateAffectedEntries(PluginModelManager.java:397)
        at org.eclipse.pde.internal.core.PluginModelManager.modelsChangedSynchronized(PluginModelManager.java:304)
        at org.eclipse.pde.internal.core.PluginModelManager.modelsChanged(PluginModelManager.java:243)
        - locked <0x00000004061b8e48> (a java.lang.Object)
        at org.eclipse.pde.internal.core.AbstractModelManager.fireModelProviderEvent(AbstractModelManager.java:37)
        at org.eclipse.pde.internal.core.WorkspaceModelManager.createAndFireEvent(WorkspaceModelManager.java:343)
        at org.eclipse.pde.internal.core.WorkspacePluginModelManager.createAndFireEvent(WorkspacePluginModelManager.java:540)
        at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:322)
        at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:280)
        at org.eclipse.pde.internal.core.WorkspacePluginModelManager.processModelChanges(WorkspacePluginModelManager.java:529)
        at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(WorkspaceModelManager.java:169)
        at org.eclipse.jdt.internal.core.DeltaProcessingState$1.run(DeltaProcessingState.java:498)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:491)
        at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
        at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
        at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
        at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:458)
        at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1586)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:50)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
"Worker-300: Performing API Analysis":
        at org.eclipse.pde.internal.core.PluginModelManager.findModel(PluginModelManager.java:1068)
        - waiting to lock <0x00000004061b8e48> (a java.lang.Object)
        at org.eclipse.pde.core.plugin.PluginRegistry.findModel(PluginRegistry.java:116)
        at org.eclipse.pde.api.tools.internal.model.ProjectComponent.createApiTypeContainers(ProjectComponent.java:216)
        at org.eclipse.pde.api.tools.internal.model.AbstractApiTypeContainer.getApiTypeContainers(AbstractApiTypeContainer.java:183)
        - locked <0x00000004a8f5ad58> (a org.eclipse.pde.api.tools.internal.model.ProjectComponent)
        at org.eclipse.pde.api.tools.internal.model.Component.getApiTypeContainers(Component.java:131)
        at org.eclipse.pde.api.tools.internal.model.AbstractApiTypeContainer.getPackageNames(AbstractApiTypeContainer.java:164)
        at org.eclipse.pde.api.tools.internal.builder.ReferenceAnalyzer.extractReferences(ReferenceAnalyzer.java:205)
        at org.eclipse.pde.api.tools.internal.builder.ReferenceAnalyzer.analyze(ReferenceAnalyzer.java:239)
        at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.checkApiUsage(BaseApiAnalyzer.java:1248)
        at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.analyzeComponent(BaseApiAnalyzer.java:288)
        at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.buildAll(ApiAnalysisBuilder.java:912)
        at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.work(ApiAnalysisBuilder.java:407)
        at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder$ApiAnalysisJob.run(ApiAnalysisBuilder.java:553)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Found 1 deadlock.
```

**Comment by laeubi** [comment]
> I believe the **main issue** is however that `WorkspaceDeltaProcessor.processJavaElementDeltas()` calls to `ApiBaselineManager.disposeWorkspaceBaseline()` **while** API analysis is running.

Yes thats also the reason sometimes in the past why the test goes wild.

Basically it would be required that a baseline has a R/W lock and everyone that wants to read the baseline (e.g. ApiAnalysisJob) acquires a read lock on it, everyone that wants to write it (e.g. dispose) needs to aquire a write lock so all readers can finish before it is actually disposed, then disposing should happen in a background job/thread as well.
