### ISSUE TITLE
Parallel API Analysis: IllegalStateException: The bundle belongs to another state

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#1107]
```
java.lang.IllegalStateException: The bundle belongs to another state: org.eclipse.help_3.10.200.v20231106-1240
	at org.eclipse.osgi.internal.resolver.StateImpl.basicAddBundle(StateImpl.java:734)
	at org.eclipse.osgi.internal.resolver.StateImpl.addBundle(StateImpl.java:199)
	at org.eclipse.pde.api.tools.internal.model.ApiBaseline.addApiComponents(ApiBaseline.java:414)
	at org.eclipse.pde.api.tools.internal.model.ApiBaseline.restoreFrom(ApiBaseline.java:800)
	at org.eclipse.pde.api.tools.internal.ApiBaselineManager.loadBaselineInfos(ApiBaselineManager.java:249)
	at org.eclipse.pde.api.tools.internal.model.ApiBaseline.loadBaselineInfos(ApiBaseline.java:772)
	at org.eclipse.pde.api.tools.internal.model.ApiBaseline.getApiComponent(ApiBaseline.java:731)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.analyzeComponent(BaseApiAnalyzer.java:239)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.buildAll(ApiAnalysisBuilder.java:917)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.work(ApiAnalysisBuilder.java:402)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder$ApiAnalysisJob.run(ApiAnalysisBuilder.java:554)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
eclipse.buildId=4.31.0.I20240131-1800
java.version=21.0.2

@iloveeclipse  i mark this as regression, as there is currently no workaround anymore to disable parallel execution

**Comment by laeubi** [comment]
Maybe better make the job / analysis more robust? Running it not as a job has major performance impact

**Comment by iloveeclipse** [comment]
> Maybe better make the job / analysis more robust?

Sure, I was only mentioning possibility to configure it in a more convenient way.

Please be aware, PDE code is a nightmare of synchronization problems, it is like a can of worms...

**Comment by iloveeclipse** [comment]
One of the problems is the baseline management with where baselines are updated / disposed on the fly, they are not atomic as of today.

**Comment by jukzi** [comment]
was removed with https://github.com/eclipse-pde/eclipse.pde/issues/307

**Comment by jukzi** [comment]
closing as parallel analysis is no default anymore
