### ISSUE TITLE
[apitools] NPE in api tools

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#1122]
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.api.tools.internal.provisional.model.IApiType.getHandle()" because "type" is null
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator$4.visit(ApiComparator.java:917)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:102)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:121)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.accept(ProjectTypeContainer.java:62)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.internalCompare(ApiComparator.java:910)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.compare(ApiComparator.java:284)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.compare(ApiComparator.java:307)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.checkCompatibility(BaseApiAnalyzer.java:1457)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.analyzeComponent(BaseApiAnalyzer.java:268)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.buildAll(ApiAnalysisBuilder.java:917)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.work(ApiAnalysisBuilder.java:408)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder$ApiAnalysisJob.run(ApiAnalysisBuilder.java:554)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Seen in todays platform sdk

**Comment by nburnwal09** [comment]
@laeubi 
Is this NPE issue still there?
If yes, what are the steps to reproduce this.

**Comment by laeubi** [comment]
I only see it occasionally and have no reproducer yet.
