### ISSUE TITLE
Support for automatic Manifest generation: Invalid thread access

### ISSUE THREAD

**Issue by mikerumpf** [eclipse-pde/eclipse.pde#1138]
While toying around with the completion proposal in the bnd file I encountered the following exception:

org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:370)
	at org.eclipse.swt.custom.StyledText.setSelectionRanges(StyledText.java:9979)
	at org.eclipse.jface.text.TextViewer.setSelectedRanges(TextViewer.java:2333)
	at org.eclipse.jface.text.TextViewer.setSelectedRange(TextViewer.java:2292)
	at org.eclipse.pde.internal.ui.bndtools.BndCompletionProcessor.computeCompletionProposals(BndCompletionProcessor.java:55)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

**Comment by laeubi** [comment]
@mikerumpf this fix should appear in the next I build tomorrow.
