### ISSUE TITLE
NPE trying to build an update site

### ISSUE THREAD

**Issue by nbros** [eclipse-pde/eclipse.pde#1144]
**With Eclipse  2023-12 (4.30).**

- org.eclipse.pde.internal.build.site.PDEState.querySystemPackages returns null for OSGi/Minimum-1.0
- org.eclipse.pde.internal.build.site.PDEState.getSystemPackages logs "No JVM system-packages available for environment OSGi/Minimum-1.0" then returns null.
- And the update site build fails with this exception:

```
!ENTRY org.eclipse.core.jobs 4 2 2024-02-09 16:32:26.473
!MESSAGE An internal error occurred during: "Build Site".
!STACK 0
java.lang.NullPointerException
	at java.base/java.util.Hashtable.put(Hashtable.java:476)
	at org.eclipse.pde.internal.build.site.PDEState.resolveState(PDEState.java:450)
	at org.eclipse.pde.internal.build.site.BuildTimeSite.getRegistry(BuildTimeSite.java:148)
	at org.eclipse.pde.internal.build.builder.BuildDirector.computeElements(BuildDirector.java:141)
	at org.eclipse.pde.internal.build.builder.BuildDirector.generateChildrenScripts(BuildDirector.java:299)
	at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:245)
	at org.eclipse.pde.internal.build.builder.BuildDirector.generateIncludedFeatureBuildFile(BuildDirector.java:283)
	at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:243)
	at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:238)
	at org.eclipse.pde.internal.build.BuildScriptGenerator.generateFeatures(BuildScriptGenerator.java:274)
	at org.eclipse.pde.internal.build.BuildScriptGenerator.generate(BuildScriptGenerator.java:151)
	at org.eclipse.pde.internal.core.exports.FeatureExportOperation.doExport(FeatureExportOperation.java:307)
	at org.eclipse.pde.internal.core.exports.FeatureBasedExportOperation.run(FeatureBasedExportOperation.java:63)
	at org.eclipse.pde.internal.core.exports.SiteBuildOperation.run(SiteBuildOperation.java:80)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by gireeshpunathil** [comment]
@nbros  - do you have a code or steps that I can follow to recreate this?
