### ISSUE TITLE
Two ClasspathResolutionTest failures since  I20240317-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1205]
We have two new ClasspathResolutionTest failures since https://download.eclipse.org/eclipse/downloads/drops4/I20240317-1800/

See for example https://download.eclipse.org/eclipse/downloads/drops4/I20240317-1800/testresults/html/org.eclipse.pde.ui.tests_ep432I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Most likely regression from ab28042c7d6616e422203cf4d731fea9a923b062 that added new dependencies.

```
org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest	testImportSystemPackageDoesntAddExtraBundleJava8	Failure	Expecting empty but was: ["org.osgi.annotation.versioning_1.1.2.202109301733.jar", "org.osgi.annotation.bundle_2.0.0.202202082230.jar", "org.osgi.service.component.annotations_1.5.1.202212101352.jar", "org.osgi.service.metatype.annotations_1.4.1.202109301733.jar"]

java.lang.AssertionError:
Expecting empty but was: ["org.osgi.annotation.versioning_1.1.2.202109301733.jar",
"org.osgi.annotation.bundle_2.0.0.202202082230.jar",
"org.osgi.service.component.annotations_1.5.1.202212101352.jar",
"org.osgi.service.metatype.annotations_1.4.1.202109301733.jar"]
at org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest.testImportSystemPackageDoesntAddExtraBundleJava8(ClasspathResolutionTest.java:132)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
```

```
org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest	testImportSystemPackageDoesntAddExtraBundleJava8_osgiEERequirement	Failure	Expecting empty but was: ["org.osgi.annotation.versioning_1.1.2.202109301733.jar", "org.osgi.annotation.bundle_2.0.0.202202082230.jar", "org.osgi.service.component.annotations_1.5.1.202212101352.jar", "org.osgi.service.metatype.annotations_1.4.1.202109301733.jar"]

java.lang.AssertionError:
Expecting empty but was: ["org.osgi.annotation.versioning_1.1.2.202109301733.jar",
"org.osgi.annotation.bundle_2.0.0.202202082230.jar",
"org.osgi.service.component.annotations_1.5.1.202212101352.jar",
"org.osgi.service.metatype.annotations_1.4.1.202109301733.jar"]
at org.eclipse.pde.core.tests.internal.classpath.ClasspathResolutionTest.testImportSystemPackageDoesntAddExtraBundleJava8_osgiEERequirement(ClasspathResolutionTest.java:146)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:276)
```

**Comment by laeubi** [comment]
Any reason these tests are not executed as part of the verification?

**Comment by laeubi** [comment]
I now checked this and the test actually *is* run but succeeds, this is likely because it is not running in a full IDE, I'll try to adjust the test setup.

**Comment by laeubi** [comment]
Fixed the test setup to show the problem here:
- https://github.com/eclipse-pde/eclipse.pde/pull/1207

this also includes a fix for the assertions now so they don't assert empty (what was just a side effect) but absence of the item.
