### ISSUE TITLE
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/

### ISSUE THREAD

**Issue by basilevs** [eclipse-pde/eclipse.pde#1214]
# Prerequisites
- Two distinct installations of Java
- Eclipse IDE for Eclipse Committers 2024-03

## Test steps
- Open a fresh empty workspace
- Create a single project of General type (no natures, no builders)
- Restart
- Open Preferences/Plugin Dvelopment/Target platform (no need to change anything, just make sure the page opens)
- Open Preferences/Java/Installed JREs
- Add (or remove) a second installation of Java
- Hit Apply and Close

Note: to reproduce repeatedly, repeat last 3 steps

## Expected result
No errors

## Actual result

```
eclipse.buildId=4.31.0.20240307-1200
java.version=17.0.4.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_GE
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.committers.product

org.eclipse.core.jobs
Error
Fri Mar 29 14:34:41 GET 2024
An internal error occurred during: "Re-resolve Target state after VM-Install or EE change".

java.lang.IllegalArgumentException: Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:68)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:144)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:416)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:88)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:341)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2398)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:601)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:642)
	at org.eclipse.core.internal.resources.Project.build(Project.java:162)
	at org.eclipse.pde.internal.core.MinimalState.reloadSystemPackagesIntoState(MinimalState.java:339)
	at org.eclipse.pde.internal.core.MinimalState$2.runInWorkspace(MinimalState.java:312)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

# Workaround
Keep a dummy project with PDE nature in the workspace.

Also observed when [RCPTT loads an Appllication Under Test with a new VM](https://github.com/eclipse/org.eclipse.rcptt/issues/60)

**Comment by basilevs** [comment]
[ManifestConsistencyChecker](https://github.com/eclipse-pde/eclipse.pde/blame/203a2c10e860b6c5e2ddde659d6f1e68b804ae49/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/builders/ManifestConsistencyChecker.java#L480) wants to lock all PDE projects and produces an empty MultiRule:

```java
	@Override
	public ISchedulingRule getRule(int kind, Map<String, String> args) {
		return new MultiRule(Arrays.stream(getProject().getWorkspace().getRoot().getProjects())
				.filter(PDEBuilderHelper::isPDEProject).toArray(ISchedulingRule[]::new));
	}
```

Empty MultiRule does not conflict with workspace root, and fails in the context of  the whole-workspace operation. ManifestConsistencyChecker should probably return null if it is not interested in any projects.
