### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.core.plugin.ModelEntry.getWorkspaceModels()" because "entry" is null

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#133]
In 
Eclipse SDK
Version: 2022-06 (4.24)
Build id: I20220530-1800
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.2+8
Java version: 17.0.2

I see the following entry in my log.

java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.core.plugin.ModelEntry.getWorkspaceModels()" because "entry" is null
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupDirector.getSourceContainers(PDESourceLookupDirector.java:99)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupQuery.getSourceContainers(PDESourceLookupQuery.java:321)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupQuery.getSourceElement(PDESourceLookupQuery.java:283)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupQuery.searchClasspathEntries(PDESourceLookupQuery.java:228)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupQuery.findSourceElement(PDESourceLookupQuery.java:183)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupQuery.findSourceElement(PDESourceLookupQuery.java:125)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupQuery.run(PDESourceLookupQuery.java:73)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.pde.internal.launching.sourcelookup.PDESourceLookupDirector.getSourceElement(PDESourceLookupDirector.java:70)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.doSourceLookup(JavaDebugUtils.java:399)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.resolveSourceElement(JavaDebugUtils.java:393)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.resolveSourceElement(JavaDebugUtils.java:360)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.resolveJavaElement(JavaDebugUtils.java:309)
	at org.eclipse.jdt.internal.debug.core.JavaDebugUtils.resolveType(JavaDebugUtils.java:111)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.EvaluationSourceGenerator.getSource(EvaluationSourceGenerator.java:390)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine.getCompiledExpression(ASTEvaluationEngine.java:396)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine.evaluate(ASTEvaluationEngine.java:154)
	at org.eclipse.jdt.internal.debug.ui.actions.EvaluateAction$1.run(EvaluateAction.java:261)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by vogella** [comment]
@HannesWell can you have a look? Sounds related to https://github.com/eclipse-pde/eclipse.pde/pull/93

**Comment by vogella** [comment]
I get this while running JUnit Plug-in Tests for WindowBuilder

![image](https://user-images.githubusercontent.com/139910/171199458-b543a396-b41d-43dd-a8d6-4a3920c713a4.png)

**Comment by merks** [comment]
This very old code seems to assume that the entry can never be null which is apparently a bad but very old assumption:

![image](https://user-images.githubusercontent.com/208716/171351677-81f43b01-69e7-4179-bf89-ee4728203b48.png)

**Comment by HannesWell** [comment]
> This very old code seems to assume that the entry can never be null which is apparently a bad but very old assumption:

Yes a simple null-check should fix the problem.

**Comment by HannesWell** [comment]
@vogella can you please verify this is fixed?
