### ISSUE TITLE
[win] tests: 'The directory name is invalid' since I20240710-0530

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#1333]
https://download.eclipse.org/eclipse/downloads/drops4/I20240710-0530/testresults/html/org.eclipse.pde.junit.runtime.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20240710-1800/testresults/html/org.eclipse.pde.junit.runtime.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.html
```
	Exception occurred executing command line.

org.eclipse.core.runtime.CoreException: Exception occurred executing command line.
at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:1013)
at org.eclipse.jdt.launching.AbstractVMRunner.exec(AbstractVMRunner.java:116)
at org.eclipse.jdt.internal.launching.StandardVMRunner.run(StandardVMRunner.java:538)
at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:286)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
at org.eclipse.debug.ui.DebugUITools.buildAndLaunch(DebugUITools.java:1030)
at org.eclipse.pde.junit.runtime.tests.TestExecutionUtil.launchAndWaitForTermination(TestExecutionUtil.java:126)
at org.eclipse.pde.junit.runtime.tests.TestExecutionUtil.runTest(TestExecutionUtil.java:81)
at org.eclipse.pde.junit.runtime.tests.JUnitExecutionTest.executeMethod(JUnitExecutionTest.java:129)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:267)
Caused by: java.io.IOException: Cannot run program "C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin\javaw.exe" (in directory "C:\Users\genie.releng\releng\workspace\AutomatedTests\ep433I-unit-win32-java17\workarea\I20240710-0530\eclipse-testing\test-eclipse\eclipse\plugins\org.eclipse.pde.junit.runtime.tests_3.7.300.v20240519-1449\test-bundles\verification.tests.junit4.platform.fragment"): CreateProcess error=267, The directory name is invalid
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:1009)
... 12 more
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
at java.base/java.lang.ProcessImpl.create(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 15 more
```

**Comment by iloveeclipse** [comment]
I assume this cold be regression from ece4417f0ca5ca66640866a1670c0fe45ef4614a. 
@HannesWell : could you please check?

**Comment by HannesWell** [comment]
> I assume this cold be regression from ece4417f0ca5ca66640866a1670c0fe45ef4614a. 
> @HannesWell : could you please check?

Since the root exception says that the directory name is invalid I think it is more likely a regression from https://github.com/eclipse-cbi/jiro/pull/379.

I'll investigate it in more detail tomorrow.

**Comment by HannesWell** [comment]
> Caused by: java.io.IOException: Cannot run program "C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin\javaw.exe" (in directory "C:\Users\genie.releng\releng\workspace\AutomatedTests\ep433I-unit-win32-java17\workarea\I20240710-0530\eclipse-testing\test-eclipse\eclipse\plugins\org.eclipse.pde.junit.runtime.tests_3.7.300.v20240519-1449\test-bundles\verification.tests.junit4.platform.fragment"): CreateProcess error=267, The directory name is invalid

This path has 264 characters and is therefore longer than the 260 characters permitted by default on Windows.
I have now created an issue to ask the Infra-team to disable that limit, which I think is the most sustainable and also the simplest solution:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4832

**Comment by HannesWell** [comment]
Test failure fixed in https://download.eclipse.org/eclipse/downloads/drops4/I20240730-1800/testResults.php
