### ISSUE TITLE
Failed to init ct.sym for /usr/lib/jvm/java-21-openjdk-amd64/lib/jrt-fs.jar during creation of new Plug-in project

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1357]
With Eclipse SDK
Version: ${releaseName} (${releaseNumberSDK})
Build id: ${buildId}
OS: Linux, v.6.8.0-38-generic, x86_64 / gtk 3.24.41, WebKit 2.44.2
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.9+9
Java version: 17.0.9

I get the following exception if I try to create a new plug-in project 

cc @HannesWell 

org.eclipse.core.runtime.CoreException: Failed to init ct.sym for /usr/lib/jvm/java-21-openjdk-amd64/lib/jrt-fs.jar
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:78)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:176)
	at org.eclipse.jdt.launching.JavaRuntime.querySystemPackages(JavaRuntime.java:3575)
	at org.eclipse.jdt.launching.JavaRuntime.lambda$0(JavaRuntime.java:3503)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.jdt.launching.JavaRuntime.getProvidedVMPackages(JavaRuntime.java:3501)
	at org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(PDEState.java:625)
	at org.eclipse.pde.internal.build.site.PDEState.lambda$10(PDEState.java:551)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:361)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(PDEState.java:552)
	at org.eclipse.pde.internal.build.site.PDEState.getSystemPackages(PDEState.java:489)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getSystemPackages(TargetPlatformHelper.java:393)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.addEnvironmentProperties(TargetPlatformHelper.java:380)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getPlatformProperties(TargetPlatformHelper.java:367)
	at org.eclipse.pde.internal.core.MinimalState.initializePlatformProperties(MinimalState.java:262)
	at org.eclipse.pde.internal.core.PDEState.<init>(PDEState.java:70)
	at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:578)
	at org.eclipse.pde.internal.core.PluginModelManager.getState(PluginModelManager.java:1202)
	at org.eclipse.pde.internal.core.bnd.TargetRepository.getTargetPlatformState(TargetRepository.java:217)
	at org.eclipse.pde.internal.core.bnd.TargetRepository.bundles(TargetRepository.java:190)
	at org.eclipse.pde.internal.core.bnd.TargetRepository.findProvider(TargetRepository.java:174)
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at aQute.bnd.osgi.resource.ResourceUtils.findProviders(ResourceUtils.java:818)
	at org.eclipse.pde.internal.core.bnd.TargetRepository.findProviders(TargetRepository.java:169)
	at org.eclipse.pde.bnd.ui.templating.ReposTemplateLoader.lambda$1(ReposTemplateLoader.java:149)
	at org.osgi.util.promise.DeferredPromiseImpl$Submit.run(DeferredPromiseImpl.java:767)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.FileNotFoundException: File /usr/lib/jvm/java-21-openjdk-amd64/lib/ct.sym does not exist
	at org.eclipse.jdt.internal.compiler.util.CtSym.init(CtSym.java:130)
	at org.eclipse.jdt.internal.compiler.util.CtSym.<init>(CtSym.java:123)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.lambda$2(JRTUtil.java:202)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1955)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getCtSym(JRTUtil.java:199)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:76)

**Comment by iloveeclipse** [comment]
Which package provides /usr/lib/jvm/java-21-openjdk-amd64/ ?

It looks like **JRE**, not **JDK**, which is required for JDT.

**Comment by HannesWell** [comment]
> Which package provides /usr/lib/jvm/java-21-openjdk-amd64/ ?
> 
> It looks like **JRE**, not **JDK**, which is required for JDT.

IIRC I read something that this split would no longer exist with modern JDKs? But I'm not an expert on this area. Or is this related to runtimes created with jlink?
Hower I do remember from the top of my head that I had some problems in the past when for example JDT detected my local jextract installation as VM-installation. But it might have been a different problem. 

In general it would of course be nice if JDT(-Debug) would refuse to use insufficient JDK/JREs as early as possible.

**Comment by pcdavid** [comment]
FWIW, I've had a similar issue for a while (Fedora 43) and finally was annoyed enough to dig into it.

Like @vogella I use sdkman to manage my JDKs, *but* `libreoffice-ure-1` has a dependency to Java and caused the system-wide installation of a minimal `java-25-openjdk-headless`, without all the files expected by PDE. In my case, installing `java-25-openjdk-jmods` explicitly added the missing `/usr/lib/jvm/java-25-openjdk/lib/ct.sym` and seems to have fixed the issue.
