### ISSUE TITLE
NPE when open a MANIFEST.MF file in editor and deleting project.

### ISSUE THREAD

**Issue by peddaiahjuturu** [eclipse-pde/eclipse.pde#1374]
I see below NPE after MANIFEST.MF file opened in the editor and delete project.
Cannot invoke "org.eclipse.pde.internal.core.ibundle.IBundle.getManifestHeader(String)" because the return value of "org.eclipse.pde.internal.ui.editor.plugin.GeneralInfoSection.getBundle()" is null
Cannot invoke "org.eclipse.pde.internal.core.ibundle.IBundle.getManifestHeader(String)" because the return value of "org.eclipse.pde.internal.ui.editor.plugin.GeneralInfoSection.getBundle()" is null

seen in Eclipse Modeling Tools

Version: 2024-06 (4.32.0)
Build id: 20240606-1231

**Comment by HannesWell** [comment]
Can you provide a full-stack trace of the NPE?

Are you interested in providing a fix for it?

**Comment by peddaiahjuturu** [comment]
@HannesWell , i`m interested in providing the fix, i hope, i get support from you in this initial stage. I already tried pushing the fix, i`m getting push not permitted issue, i`ll try again today.

**Comment by peddaiahjuturu** [comment]
Below if the full-stack trace.
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.internal.core.ibundle.IBundle.getManifestHeader(String)" because the return value of "org.eclipse.pde.internal.ui.editor.plugin.GeneralInfoSection.getBundle()" is null
	at org.eclipse.pde.internal.ui.editor.plugin.GeneralInfoSection.refresh(GeneralInfoSection.java:357)
	at org.eclipse.pde.internal.ui.editor.plugin.PluginGeneralInfoSection.refresh(PluginGeneralInfoSection.java:195)
	at org.eclipse.ui.forms.ManagedForm.doRefresh(ManagedForm.java:181)
	at org.eclipse.ui.forms.ManagedForm.refresh(ManagedForm.java:171)
	at org.eclipse.ui.forms.editor.FormPage$PageForm.staleStateChanged(FormPage.java:61)
	at org.eclipse.ui.forms.AbstractFormPart.markStale(AbstractFormPart.java:131)
	at org.eclipse.pde.internal.ui.editor.plugin.GeneralInfoSection.modelChanged(GeneralInfoSection.java:322)
	at org.eclipse.pde.internal.core.AbstractModel.fireModelChanged(AbstractModel.java:125)
	at org.eclipse.pde.internal.core.bundle.BundlePluginModelBase.fireModelChanged(BundlePluginModelBase.java:158)
	at org.eclipse.pde.internal.ui.editor.plugin.PluginInputContextManager.transferListeners(PluginInputContextManager.java:135)
	at org.eclipse.pde.internal.ui.editor.plugin.PluginInputContextManager.bundleRemoved(PluginInputContextManager.java:126)
	at org.eclipse.pde.internal.ui.editor.plugin.PluginInputContextManager.fireContextChange(PluginInputContextManager.java:77)
	at org.eclipse.pde.internal.ui.editor.context.InputContextManager.removeContext(InputContextManager.java:270)
	at org.eclipse.pde.internal.ui.editor.context.InputContextManager.structureChanged(InputContextManager.java:259)
	at org.eclipse.pde.internal.ui.editor.plugin.PluginInputContextManager.structureChanged(PluginInputContextManager.java:65)
	at org.eclipse.pde.internal.ui.editor.context.InputContextManager.lambda$1(InputContextManager.java:244)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:354)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:230)
	at org.eclipse.ui.internal.progress.ProgressManager.run(ProgressManager.java:973)
	at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1105)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$27(ProgressManager.java:985)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4058)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3676)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:168)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:370)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.run(RefactoringWizardDialog2.java:325)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.internalPerformFinish(RefactoringWizard.java:636)
	at org.eclipse.ltk.ui.refactoring.UserInputWizardPage.performFinish(UserInputWizardPage.java:148)
	at org.eclipse.ltk.ui.refactoring.resource.DeleteResourcesWizard$DeleteResourcesRefactoringConfigurationPage.performFinish(DeleteResourcesWizard.java:284)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.performFinish(RefactoringWizard.java:710)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.okPressed(RefactoringWizardDialog2.java:451)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:265)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.lambda$0(RefactoringWizardOpenOperation.java:190)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:209)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:126)
	at org.eclipse.ltk.internal.ui.refactoring.actions.DeleteResourcesHandler.execute(DeleteResourcesHandler.java:44)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommandInContext(LegacyHandlerService.java:436)
	at org.eclipse.ui.internal.ide.actions.LTKLauncher.runCommand(LTKLauncher.java:140)
	at org.eclipse.ui.internal.ide.actions.LTKLauncher.openDeleteWizard(LTKLauncher.java:57)
	at org.eclipse.ui.actions.DeleteResourceAction.run(DeleteResourceAction.java:452)
	at org.eclipse.jdt.internal.ui.refactoring.reorg.DeleteAction.run(DeleteAction.java:197)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:274)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:252)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)

**Comment by merks** [comment]
You need to contribute by creating a pull request.  Some some generic details about how to create a pull request via your fork is documented here:

https://github.com/orgs/eclipse-simrel/discussions/3

Probably there are other places with such documentation, but I don't see any links to them...

**Comment by merks** [comment]
@laeubi @HannesWell 

A meta-question.  Do any of our "contributing "links provide links for how to work with forks and pull requests?  I know we assume most people know this, but definitely not all people know this.

**Comment by peddaiahjuturu** [comment]
> > Probably there are other places with such documentation, but I don't see any links to them...
> 
> * https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks
> * https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

This helped me to raise a PR, Thanks

**Comment by HannesWell** [comment]
> @laeubi @HannesWell
> 
> A meta-question. Do any of our "contributing "links provide links for how to work with forks and pull requests? I know we assume most people know this, but definitely not all people know this.

Not yet, but for the https://github.com/eclipse-ide we (Community Mentors) plan to have a comprehensive guide on how to contribute to the Eclipse-IDE (which definitively includes all the SDK projects).
I just added the links to my draft at https://github.com/eclipse-ide/.github/pull/1 (although it already contains other links from that section).

**Comment by HannesWell** [comment]
Thanks @peddaiahjuturu for providing a fix for this issue.
You can verify with the I-build that will be built tonight that this issue is really fixed. It will probably be available at
https://download.eclipse.org/eclipse/downloads/drops4/I20240815-1800/

Or you can simply try the latest `Integration Builds` from
https://download.eclipse.org/eclipse/downloads/index.html
