### ISSUE TITLE
org.eclipse.ua.tests.doc failure since I20240904-0530

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#1392]
See

* https://download.eclipse.org/eclipse/downloads/drops4/I20240904-0530/testResults.php
* https://download.eclipse.org/eclipse/downloads/drops4/I20240905-0340/testresults/html/org.eclipse.ua.tests.doc_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
TocLinkChecker	testPdeUserGenerated()	Failure	Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/overview-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/api/tools/annotations/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/build/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/build/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/plugin/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/project/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/target/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/launching/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/launcher/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/target/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/templates/package-summary.html

java.lang.AssertionError: Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/overview-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/api/tools/annotations/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/build/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/build/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/plugin/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/project/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/target/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/launching/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/launcher/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/target/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/templates/package-summary.html

at org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.doAssert(TocLinkChecker.java:128)
at org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.testPdeUserGenerated(TocLinkChecker.java:102)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by akurtakov** [comment]
And these files are actually missing from pde.doc bundle so smth went wrong with building javadoc.

**Comment by iloveeclipse** [comment]
Yep, was my assumption too.

**Comment by jukzi** [comment]
does it relate to https://ci.eclipse.org/pde/job/eclipse.pde/job/master/739/consoleText contain 12 times `Error while generating Javadoc`?

**Comment by iloveeclipse** [comment]
Exact. Now we only need to know where it is coming from.

**Comment by iloveeclipse** [comment]
Usually that would be some missing library/classpath change, but I'm not aware about recent changes in any platform area that would affect PDE build.

**Comment by jukzi** [comment]
10 of them are old - already in https://ci.eclipse.org/pde/job/eclipse.pde/job/master/735/consoleText
The last 2 are new:
```
TargetDefinitionResolutionTests.java:73: error: reference not found
[2024-09-04T09:23:24.347Z] 	 * @see TargetBundle.STATUS_INVALID_MANIFEST

```
 @HannesWell 

and
```
TestCompositeSearchReporter.java:25: error: reference not found
[2024-09-04T09:26:48.445Z]  * reporters: The {@link TestReporter} and the {@link XMLApiSearchReporter}
...
```
no changes in TestCompositeSearchReporter for 6 years

**Comment by HannesWell** [comment]
> `Error while generating `

I wonder why the overall build then doesn't fail?

**Comment by HannesWell** [comment]
> > `Error while generating `
> 
> I wonder why the overall build then doesn't fail?

I have now configured the build to fail on javadoc erros and fixed all remaining javadoc errors with:
- https://github.com/eclipse-pde/eclipse.pde/pull/1400

So this should hopefully be fixed with tonight's I-build.

**Comment by iloveeclipse** [comment]
Still there: https://download.eclipse.org/eclipse/downloads/drops4/I20240908-1800/testresults/html/org.eclipse.ua.tests.doc_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

**Comment by HannesWell** [comment]
> Still there: https://download.eclipse.org/eclipse/downloads/drops4/I20240908-1800/testresults/html/org.eclipse.ua.tests.doc_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

It's still the same error as initially. So fixing all the erroneous javadoc didn't help 😞

```
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/overview-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/api/tools/annotations/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/build/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/build/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/plugin/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/project/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/target/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/launching/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/launcher/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/target/package-summary.html
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/templates/package-summary.html 
```



> does it relate to https://ci.eclipse.org/pde/job/eclipse.pde/job/master/739/consoleText contain 12 times `Error while generating Javadoc`?

Unfortunately I cannot check the output of the latest master build since Jenkins has again a Gateway timeout...
But IIRC there was no such error anymore with #1400.

**Comment by HannesWell** [comment]
Verified that the test succeeds in the latest I-Build as well as in eclipse-platform repo verification builds.

Since the build now also fails on Javadoc errors the Javadoc should now stay in good shape for PDE.

If possible it would also be simpler to address future issues if the `TocTocChecker.testPdeUserGenerated()` test would be executed in this repo (too).
