### ISSUE TITLE
Cannot not open launching tab in product editor - java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.internal.core.iproduct.ILauncherInfo.getMacBundleUrlTypes()" because the return value of "org.eclipse.pde.internal.core.iproduct.IProduct.getLauncherInfo()" is null

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#1443]
Eclipse SDK
Version: 2024-12 (4.34)
Build id: I20241016-0020
OS: Linux, v.6.8.0-45-generic, x86_64 / gtk 3.24.41
Java vendor: Ubuntu
Java runtime version: 21.0.4+7-Ubuntu-1ubuntu224.04
Java version: 21.0.4

Trying to open a product launching tab results in an exception.

java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.internal.core.iproduct.ILauncherInfo.getMacBundleUrlTypes()" because the return value of "org.eclipse.pde.internal.core.iproduct.IProduct.getLauncherInfo()" is null
	at org.eclipse.pde.internal.ui.editor.product.LauncherSection$MacBundleUrlTypesComposite.lambda$3(LauncherSection.java:422)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:941)
	at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:702)
	at org.eclipse.jface.viewers.AbstractTableViewer.getRawChildren(AbstractTableViewer.java:1107)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:849)
	at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1025)
	at org.eclipse.jface.viewers.ColumnViewer.getSortedChildren(ColumnViewer.java:821)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefreshAll(AbstractTableViewer.java:670)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:616)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:608)
	at org.eclipse.jface.viewers.AbstractTableViewer.lambda$0(AbstractTableViewer.java:562)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1392)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1353)
	at org.eclipse.jface.viewers.AbstractTableViewer.inputChanged(AbstractTableViewer.java:562)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1636)
	at org.eclipse.pde.internal.ui.editor.product.LauncherSection$MacBundleUrlTypesComposite.<init>(LauncherSection.java:426)
	at org.eclipse.pde.internal.ui.editor.product.LauncherSection.addMacSection(LauncherSection.java:359)
	at org.eclipse.pde.internal.ui.editor.product.LauncherSection.createClient(LauncherSection.java:213)
	at org.eclipse.pde.internal.ui.editor.product.LauncherSection.<init>(LauncherSection.java:160)
	at org.eclipse.pde.internal.ui.editor.product.LaunchingPage.fillBody(LaunchingPage.java:58)
	at org.eclipse.pde.internal.ui.editor.product.LaunchingPage.createFormContent(LaunchingPage.java:49)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.pde.internal.ui.editor.PDEFormPage.createPartControl(PDEFormPage.java:296)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at org.eclipse.pde.internal.ui.editor.PDEFormEditor.pageChange(PDEFormEditor.java:283)
	at org.eclipse.ui.part.MultiPageEditorPart.lambda$1(MultiPageEditorPart.java:270)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:265)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1626)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1373)

![image](https://github.com/user-attachments/assets/5725e97f-e186-4e08-8e53-3d5f65ae9a9a)

**Comment by vogella** [comment]
Works fine in an older Eclipse, e.g. Build id: I20231204-1800
