### ISSUE TITLE
Getting a Null Pointer Exception, system packages are not available

### ISSUE THREAD

**Issue by Khushboo-Sharma-110597** [eclipse-pde/eclipse.pde#1453]
I am getting below exception.
getSystemPackage is returning null for my case because i dont have any value present for org.osgi.framework.system.packages
and i am getting null pointer pointer exception due to that , there should be null pointer check inside resolveState function, this check is maintained everywhere but it is missing in resolveState only
java.lang.NullPointerException
at java.base/java.util.Hashtable.put(Hashtable.java:476)
at org.eclipse.pde.internal.build.site.PDEState.resolveState(PDEState.java:444)
at org.eclipse.pde.internal.build.site.BuildTimeSite.getRegistry(BuildTimeSite.java:147)
at org.eclipse.pde.internal.build.builder.BuildDirector.computeElements(BuildDirector.java:140)
at org.eclipse.pde.internal.build.builder.BuildDirector.generateChildrenScripts(BuildDirector.java:295)
at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:244)
at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:237)
at org.eclipse.pde.internal.build.BuildScriptGenerator.generateFeatures(BuildScriptGenerator.java:265)
at org.eclipse.pde.internal.build.BuildScriptGenerator.generate(BuildScriptGenerator.java:147)
at org.eclipse.pde.internal.core.exports.FeatureExportOperation.doExport(FeatureExportOperation.java:310)
at org.eclipse.pde.internal.core.exports.FeatureBasedExportOperation.run(FeatureBasedExportOperation.java:63)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

my profileProps looks like this
profileProps = {org.osgi.framework.bootdelegation=sun.,com.sun., org.osgi.framework.executionenvironment=OSGi/Minimum-1.0, org.eclipse.jdt.core.compiler.problem.assertIdentifier=ignore, org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.1, org.osgi.framework.system.capabilities=osgi.ee; osgi.ee="OSGi/Minimum"; version:Version="1.0", org.eclipse.jdt.core.compiler.source=1.3, org.osgi.framework.system.packages=, osgi.java.profile.name=OSGi/Minimum-1.0, org.eclipse.jdt.core.compiler.problem.enumIdentifier=ignore, org.eclipse.jdt.core.compiler.compliance=1.3}

**Comment by sharmakh** [comment]
i have raised a pr for this, please review
https://github.com/eclipse-pde/eclipse.pde/pull/1454
