### ISSUE TITLE
[product launch] element cannot be mapped to a null key

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#185]
@HannesWell I try to build a product for m2e with just the m2e features using the new automatic added dependencies, but this currently fails with:

```
java.lang.NullPointerException: element cannot be mapped to a null key
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1127)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getPrioritizedAvailableFeatures(BundleLauncherHelper.java:247)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getSelectedFeatures(BundleLauncherHelper.java:198)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getMergedBundleMapFeatureBased(BundleLauncherHelper.java:135)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getMergedBundleMap(BundleLauncherHelper.java:94)
	at org.eclipse.pde.launching.EclipseApplicationLaunchConfiguration.preLaunchCheck(EclipseApplicationLaunchConfiguration.java:192)
	at org.eclipse.pde.launching.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:115)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Product file:
```
<?xml version="1.0" encoding="UTF-8"?>
<?pde version="3.5"?>

<product name="M2Eclipse IDE for testing purpose" uid="m2e-ide" application="org.eclipse.ui.ide.workbench" version="2.0.0" useFeatures="true" includeLaunchers="false" autoIncludeRequirements="true">

   <configIni use="default">
   </configIni>

   <launcherArgs>
      <vmArgsMac>-XstartOnFirstThread -Dorg.eclipse.swt.internal.carbon.smallFonts
      </vmArgsMac>
   </launcherArgs>

   <launcher>
      <win useIco="false">
         <bmp/>
      </win>
   </launcher>

   <vm>
   </vm>

   <plugins>
   </plugins>

   <features>
      <feature id="org.eclipse.m2e.feature" installMode="root"/>
      <feature id="org.eclipse.m2e.lemminx.feature" installMode="root"/>
      <feature id="org.eclipse.m2e.logback.feature" installMode="root"/>
      <feature id="org.eclipse.m2e.pde.feature" installMode="root"/>
   </features>

   <configurations>
      <plugin id="org.apache.felix.scr" autoStart="true" startLevel="2" />
      <plugin id="org.eclipse.core.runtime" autoStart="true" startLevel="0" />
      <plugin id="org.eclipse.equinox.common" autoStart="true" startLevel="2" />
      <plugin id="org.eclipse.equinox.event" autoStart="true" startLevel="2" />
      <plugin id="org.eclipse.equinox.simpleconfigurator" autoStart="true" startLevel="1" />
   </configurations>

</product>
```

**Comment by HannesWell** [comment]
> ```
> java.lang.NullPointerException: element cannot be mapped to a null key
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
> 	...
> 	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getPrioritizedAvailableFeatures(BundleLauncherHelper.java:247)

This happens at:
https://github.com/eclipse-pde/eclipse.pde/blob/3f49bb4055be34cfc3323af341e6f37b49d01484/ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java#L247

From the error message that location I strongly suspect that there is a Feature in your Workspace or Target-Platform whose Id is `null`. At this point all Features in the TP and workspace are collected. So this is not a problem with the Product configuration itself but with the environment.
While the error can be fixed easily by filtering out features with null Id it would also be interesting to know how this happens and I think it should be better to avoid that earlier because otherwise users may wonder why a certain plug-in is missing in the launched application, without obvious reason. 
So either we should fail here with a more descriptive message or at least log a warning so that there is a better chance to find out what is happening.

For features in the workspace you actually get an error when the Id attribute is missing. Did you change that preference?
![grafik](https://user-images.githubusercontent.com/44067969/175763811-65fa13fc-76ad-4482-95f3-fd48ac3adb24.png)


Do you know if it is possible to build a feature with Tycho that has no id set and can therefore end in a TP?

**Comment by laeubi** [comment]
No idea how this happens, but I have a lot of stuff in my workspace and some for debugging, maybe a project that currently has compile errors is causing this.

Neverless I think a warning that prints the location of the offending feature would be suitable here.

**Comment by HannesWell** [comment]
> No idea how this happens, but I have a lot of stuff in my workspace and some for debugging, maybe a project that currently has compile errors is causing this.
>

Very likely. I was able to reproduce the failure by accident when I just tried to launch an Eclipse from my PDE workspace to test good error message from my PDE workspace after I created a flawed feature:

![grafik](https://user-images.githubusercontent.com/44067969/175764538-4a93f813-d67a-47c9-9160-de72c0a4f4b1.png)


> 
> Neverless I think a warning that prints the location of the offending feature would be suitable here.

Yep, I'm looking for a good message. I think the location should still be available (I can't print the id obviously :D)

**Comment by HannesWell** [comment]
@laeubi can you please verify/confirm with the latest I-build or the upcomming 22-09 M1 that this issue is fixed?
