### ISSUE TITLE
SourceTests.testBug206679_247198 fails since I20220628-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#189]
After Jetty update SourceTests.testBug206679_247198 fails on all platforms.
```
testBug206679_247198 | Error 
Processing inclusion from feature org.eclipse.help: Bundle org.eclipse.equinox.http.jetty_3.8.100.v20211021-1418 failed to resolve.: Unsatisfied import package org.eclipse.jetty.http_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.server_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.server.handler_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.server.session_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.servlet_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.component_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.log_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.ssl_[10.0.2,11.0.0). Unsatisfied import package org.eclipse.jetty.util.thread_[10.0.2,11.0.0).

/home/jenkins/agent/workspace/ep425I-unit-cen64-gtk3-java11/workarea/I20220628-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.11.200.v20220503-0921/scripts/genericTargets.xml:112: Processing inclusion from feature org.eclipse.help: Bundle org.eclipse.equinox.http.jetty_3.8.100.v20211021-1418 failed to resolve.:
Unsatisfied import package org.eclipse.jetty.http_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.server_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.server.handler_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.server.session_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.servlet_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.component_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.log_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.ssl_[10.0.2,11.0.0).
Unsatisfied import package org.eclipse.jetty.util.thread_[10.0.2,11.0.0).

at org.eclipse.pde.internal.build.tasks.BuildScriptGeneratorTask.execute(BuildScriptGeneratorTask.java:98)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
at jdk.internal.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
```

https://download.eclipse.org/eclipse/downloads/drops4/I20220628-1800/testresults/html/org.eclipse.pde.build.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Comment by akurtakov** [comment]
I think this is caused by the fact I touched the jetty feature and didn't bump version leading to some "mixture"

**Comment by akurtakov** [comment]
I'll land https://github.com/eclipse-equinox/equinox/pull/67 and fire a build . Hopefully this will resolve the issue for the future.

**Comment by akurtakov** [comment]
I can't find what's the cause here. As the help system and various builds work I'm leaning towards issue in pde.build. As I'm going on vacation I won't be looking at this one in the next 2 weeks.

**Comment by akurtakov** [comment]
@HannesWell do you think you can find some time to look into this one?

**Comment by HannesWell** [comment]
> @HannesWell do you think you can find some time to look into this one?

I'll try it.

**Comment by HannesWell** [comment]
To me it looks like that the ANT-runtime somehow does not find the jettey-bundles that are included into the `org.eclipse.help` feature. But I cannot tell where it is specified what's available to ant. Is that taken from the runtime of the test? Then we just have to reference that. 

But I cannot really test that, because when I run the test in the IDE fails with another error. But I'll try a local Maven build with the tests of this module being executed.

**Comment by HannesWell** [comment]
Since I20220813-0600 the test is not failing anymore:
https://download.eclipse.org/eclipse/downloads/drops4/I20220813-0600/testresults/html/org.eclipse.pde.build.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

No clue why it is fixed, but it is.

**Comment by iloveeclipse** [comment]
Because some libraries were reverted back to orbit versions.

**Comment by iloveeclipse** [comment]
These: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/480

**Comment by HannesWell** [comment]
Interesting. When search for those bundle's name in the pde repo I found nothing that seem to be connected to pde.build or its tests.
