### ISSUE TITLE
Test failure only on linux/Mac with java 11 (testProducts_productAddedToDerivedSourceFolder)

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#21]
org.eclipse.pde.core.tests.internal.WorkspaceProductModelManagerTest | testProducts_productAddedToDerivedSourceFolder | Error | N/A                                                                           java.lang.NullPointerException                                                  	at  org.eclipse.pde.core.tests.internal.WorkspaceProductModelManagerTest.assertSingleProductWithId(WorkspaceProductModelManagerTest.java:151)                                                  	at  org.eclipse.pde.core.tests.internal.WorkspaceProductModelManagerTest.testProducts_productAddedToDerivedSourceFolder(WorkspaceProductModelManagerTest.java:87)                                                  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                  	at  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)                                                  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)                                                  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)                                                  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)                                                  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)                                                  	at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:271)                                                  	at org.junit.runners.ParentRu
-- | -- | -- | --

**Comment by vik-chand** [comment]
This could be intermittent.

**Comment by vik-chand** [comment]
This happened on Mac as well https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testresults/html/org.eclipse.pde.ui.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
