### ISSUE TITLE
WorkspacePluginModelManager: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#210]
I got the following strange exception while editing a component:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at org.eclipse.osgi.internal.module.VersionHashMap.reorder(VersionHashMap.java:87)
	at org.eclipse.osgi.internal.module.ResolverImpl.resolve(ResolverImpl.java:472)
	at org.eclipse.osgi.internal.resolver.StateImpl.resolve(StateImpl.java:602)
	at org.eclipse.osgi.internal.resolver.StateImpl.resolve(StateImpl.java:662)
	at org.eclipse.pde.internal.core.MinimalState.internalResolveState(MinimalState.java:244)
	at org.eclipse.pde.internal.core.MinimalState.resolveState(MinimalState.java:221)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChangedSynchronized(PluginModelManager.java:298)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChanged(PluginModelManager.java:244)
	at org.eclipse.pde.internal.core.AbstractModelManager.fireModelProviderEvent(AbstractModelManager.java:37)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.createAndFireEvent(WorkspaceModelManager.java:343)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.createAndFireEvent(WorkspacePluginModelManager.java:552)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:322)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:280)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.processModelChanges(WorkspacePluginModelManager.java:541)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(WorkspaceModelManager.java:169)
	at org.eclipse.jdt.internal.core.DeltaProcessingState$1.run(DeltaProcessingState.java:496)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:489)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1514)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:176)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I have no clue how to reproduce this, but post it here in the hope it will be usefull for someone or has an ide what could causing this...

**Comment by iloveeclipse** [comment]
This is not strange, it is a bug. `VersionHashMap` users should never use keys that changes their object state (hashCode() / equals() should not rely on non final fields).
Obviously some object used as a key changed the state during sort().

**Comment by laeubi** [comment]
I can now reproduce this quite good, this is sorting items of type `ResolverExport`, these are not final, but also do not implement hashCode/equals, so it is not the object itself to blame but the bug seems to be in `org.eclipse.osgi.internal.module.VersionHashMap.compare(V, V)` that do not provide a stable ordering:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at org.eclipse.osgi.internal.module.VersionHashMap.reorder(VersionHashMap.java:87)
	at org.eclipse.osgi.internal.module.ResolverImpl.resolve(ResolverImpl.java:472)
	at org.eclipse.osgi.internal.resolver.StateImpl.resolve(StateImpl.java:599)
	at org.eclipse.osgi.internal.resolver.StateImpl.resolve(StateImpl.java:659)
	at org.eclipse.pde.internal.core.MinimalState.internalResolveState(Unknown Source)
	at org.eclipse.pde.internal.core.MinimalState.resolveState(Unknown Source)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChangedSynchronized(Unknown Source)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChanged(Unknown Source)
	at org.eclipse.pde.internal.core.AbstractModelManager.fireModelProviderEvent(Unknown Source)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.createAndFireEvent(Unknown Source)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.createAndFireEvent(Unknown Source)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(Unknown Source)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(Unknown Source)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.processModelChanges(Unknown Source)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(Unknown Source)
	at org.eclipse.jdt.internal.core.DeltaProcessingState$1.run(DeltaProcessingState.java:496)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:489)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.checkpoint(Workspace.java:584)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.lambda$0(PerformChangeOperation.java:263)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:295)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:94)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:219)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

@tjwatson any idea what might cause this? I do not fully understand the compare method but it seems to vialote the contract of `compare` somehwere...

**Comment by laeubi** [comment]
One thing I noticed here is that PDE sets an own Selection Policy here in `org.eclipse.pde.internal.core.PDEState.createNewTargetState(boolean, URI[], IProgressMonitor)`

There is one comparision that looks suspicious:
https://github.com/eclipse-pde/eclipse.pde/blob/100ff6a7b394cb0857fa8769e61df2e3e40fc057/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDEState.java#L104-L121

Here further comparison is only performed if the first item ends with qualifier, but this seems to violate that if `a > b` then `b < a` but can result inf if `a > b` and then `b == a` ...

**Comment by merks** [comment]
@laeubi I was about to mention that policy override.  Note thought that if v1 != v2 we would have returned earlier so neither must have a qualifier in this case where we look at locations.   I'm not sure I see the case that's asymmetric yet...

**Comment by merks** [comment]
This seems have have been changed with a bug "Update to fix - Bug 499486 - plugin workspace dependencies ignored after
restart " so I think this is supposed to be preferring a resolution for something with a workspace location (something in the workspace)...

**Comment by merks** [comment]
@laeubi 

Maybe it should be like this?
```
					IPath p1 = new Path(loc1);
					boolean p1InWorkspace = root
							.findContainersForLocationURI(URIUtil.toURI(p1)).length != 0;
					IPath p2 = new Path(loc2);
					boolean p2InWorkspace = root
								.findContainersForLocationURI(URIUtil.toURI(p2)).length != 0;
					if (p1InWorkspace && !p2InWorkspace) {
						return -1;
					}
					if (!p1InWorkspace && p2InWorkspace) {
						return 1;
					}
```

**Comment by laeubi** [comment]
I tried this out, but didnt help, I even tried to find the offending object but nothing was triggered here:

```
public int compare(V vs1, V vs2) {
int cmp = cmp(vs1, vs2);
int cmp2 = cmp(vs2, vs1);
if (cmp != -cmp2) {
	System.out.println("COMPARE ERROR!!!"); //$NON-NLS-1$
}
boolean equals = Objects.equals(vs1, vs2);
if (equals && cmp != 0) {
	System.out.println("EQUALS COMPARE 0 error!"); //$NON-NLS-1$
}
if (equals) {
	if (!Objects.equals(vs2, vs1)) {
		System.out.println("EQUALS ERROR???!"); //$NON-NLS-1$
	}
	if (vs1.hashCode() != vs2.hashCode()) {
		System.out.println("HASH ERROR!"); //$NON-NLS-1$
	}
}
return cmp;
}
```

seems I still missing some contracts, or something in the comparing changes order but I can't see how :-\

**Comment by laeubi** [comment]
I now run a brute force transitivity check and it shows that:

```
compare A < B: -1
compare B < C: -1
compare A < C: 1
A: Export-Package: org.eclipse.jdt.internal.corext; version="0.0.0"
B: Export-Package: org.eclipse.jdt.internal.corext; version="0.0.0"
C: Export-Package: org.eclipse.jdt.internal.corext; version="0.0.0"
```

A is from [org.eclipse.jdt.core.manipulation_1.17.100.v20230124-1216]
B is from [org.eclipse.jdt.ui_3.28.0.v20230210-2115]
C is from [org.eclipse.jdt.ui_3.27.100.v20221029-1307]

A osgi.wiring.package; bundle-symbolic-name="org.eclipse.jdt.core.manipulation"; bundle-version:Version="1.17.100.v20230124-1216"; version:Version="0.0.0"; osgi.wiring.package="org.eclipse.jdt.internal.corext"; x-friends:="org.eclipse.jdt.ui"; x-internal:="false"
B osgi.wiring.package; bundle-symbolic-name="org.eclipse.jdt.ui"; bundle-version:Version="3.28.0.v20230210-2115"; version:Version="0.0.0"; osgi.wiring.package="org.eclipse.jdt.internal.corext"; x-friends:="org.eclipse.jdt.junit"; x-internal:="false"
C osgi.wiring.package; bundle-symbolic-name="org.eclipse.jdt.ui"; bundle-version:Version="3.27.100.v20221029-1307"; version:Version="0.0.0"; osgi.wiring.package="org.eclipse.jdt.internal.corext"; x-friends:="org.eclipse.jdt.junit"; x-internal:="false"

**Comment by laeubi** [comment]
So the problematic part is here:

https://github.com/eclipse-pde/eclipse.pde/blob/100ff6a7b394cb0857fa8769e61df2e3e40fc057/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDEState.java#L97-L101

and it is triggered if there are 3 bundles that export the same package with same version but not all have the same symbolic name.

In such a case, the non matching item is compared using the **BundleID** while the matching items are compared using their **Versions** ... this then leads to the problem that the transitivity is violated depending on the bundle ids because then the non matching from the set can suddenly become larger...I'm not sure how this can be solved, I think the idea is that "highest version wins" but for a package export and different supplier, there is really no way to tell what "larger" should mean ...

**Comment by laeubi** [comment]
@tjwatson my current idea is to simply assume two items are equal if their version matches, or is there any reason to have a total order of items? I don't really see how one can make a choice here in the context of PDE e.g. in an OSGi framework it might make sense to use the one with highest ID, but here there is simply no real control.

**Comment by merks** [comment]
@laeubi Very good find!
