### ISSUE TITLE
JUnit5SuiteExecutionTest fails since I20220713-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#211]
3 JUnit5SuiteExecutionTest fail since I20220713-1800 on all platforms.

https://download.eclipse.org/eclipse/downloads/drops4/I20220713-1800/testresults/html/org.eclipse.pde.junit.runtime.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

``` 
org.eclipse.pde.junit.runtime.tests.JUnit5SuiteExecutionTest | executePackage

java.lang.AssertionError: test completed with Undefined
at org.eclipse.pde.junit.runtime.tests.JUnitExecutionTest.assertSuccessful(JUnitExecutionTest.java:140)
at org.eclipse.pde.junit.runtime.tests.JUnit5SuiteExecutionTest.executePackage(JUnit5SuiteExecutionTest.java:60)
```

``` 
org.eclipse.pde.junit.runtime.tests.JUnit5SuiteExecutionTest | executeProject

java.lang.AssertionError: test completed with Undefined
at org.eclipse.pde.junit.runtime.tests.JUnitExecutionTest.assertSuccessful(JUnitExecutionTest.java:140)
at org.eclipse.pde.junit.runtime.tests.JUnit5SuiteExecutionTest.executeProject(JUnit5SuiteExecutionTest.java:67)
``` 

``` 
org.eclipse.pde.junit.runtime.tests.JUnit5SuiteExecutionTest | executeSuite

java.lang.AssertionError: test completed with Undefined
at org.eclipse.pde.junit.runtime.tests.JUnitExecutionTest.assertSuccessful(JUnitExecutionTest.java:140)
at org.eclipse.pde.junit.runtime.tests.JUnit5SuiteExecutionTest.executeSuite(JUnit5SuiteExecutionTest.java:45)
```

**Comment by iloveeclipse** [comment]
@mickaelistria : could you please check? I assume that is related to recent Orbit / Maven bundle replacements.

**Comment by mickaelistria** [comment]
Yes, I think it's a transient issue that would hopefully be fixed with upstream work on JDT and https://github.com/eclipse-pde/eclipse.pde/pull/206 . Today is a holiday in France, but I may spend a hour on it later tonight. I hope to complete this story and have it fixed by tomorrow afternoon.
