### ISSUE TITLE
Cannot invoke "org.eclipse.pde.core.plugin.ModelEntry.getWorkspaceModels()" because "swtEntries" is null

### ISSUE THREAD

**Issue by fbertini** [eclipse-pde/eclipse.pde#238]
Hello everyone,

I have installed the latest Eclipse IDE version (today it is eclipse-jee-2022-06-R-win32-x86_64.zip) and I always get the following error hovering the mouse on the RUN/debug button on the toolbar.

Cannot invoke "org.eclipse.pde.core.plugin.ModelEntry.getWorkspaceModels()" because "swtEntries" is null

Notice that this is happening only when I am working on a JUnit4 class.

PDE Version 4.24

References: [Eclipse Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=580456)

**Comment by iloveeclipse** [comment]
@fbertini : please attach here Eclipse error **log** (you can find it under <your workspace>./metadata/.log).

**Comment by fbertini** [comment]
Please find attached log file as requested.
[log.zip](https://github.com/eclipse-pde/eclipse.pde/files/9196425/log.zip)

Thank you!

**Comment by iloveeclipse** [comment]
```
!ENTRY org.eclipse.core.jobs 4 2 2022-07-27 08:27:29.045
!MESSAGE An internal error occurred during: "Compute launch button tooltip".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.core.plugin.ModelEntry.getWorkspaceModels()" because "swtEntries" is null
	at org.eclipse.pde.internal.launching.launcher.LauncherUtils.requiresUI(LauncherUtils.java:331)
	at org.eclipse.pde.ui.launcher.JUnitWorkbenchLaunchShortcut.createLaunchConfiguration(JUnitWorkbenchLaunchShortcut.java:59)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchShortcut.findExistingLaunchConfigurations(JUnitLaunchShortcut.java:590)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchShortcut.getLaunchConfigurations(JUnitLaunchShortcut.java:558)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.getLaunchConfigurations(LaunchShortcutExtension.java:496)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager.getParticipatingLaunchConfigurations(LaunchingResourceManager.java:489)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager.getLabel(LaunchingResourceManager.java:326)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager.computeLabels(LaunchingResourceManager.java:246)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager$1$1.run(LaunchingResourceManager.java:144)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by iloveeclipse** [comment]
@HannesWell : looks like regression from commit d0a6e0fd8e217fc1f108d7585012aab8b9862369 / #110

**Comment by HannesWell** [comment]
Thanks for the report.
Andrey you are right, I forgot to handle the null Case.

I can fix this in two weeks when back from vacation (only have my phone available).

If any of you want to fix it earlier, it should be sufficient  to pull up 
`ModelEntry swtEntries = PluginRegistry.findEntry("org.eclipse.swt"); //$NON-NLS-1$` as first expression in the if-block and to return false if it is null. I can review it.

**Comment by iloveeclipse** [comment]
Thanks Hannes, see https://github.com/eclipse-pde/eclipse.pde/pull/240

**Comment by HannesWell** [comment]
The version of Eclipse you mentioned should include version 1.20 of m2e PDE, which is more recent than 1.17.

Nevertheless this fix in Eclipse PDE (which is referenced by M2E-PDE) will be relesed with Eclipse 2022-09 or 4.25 in September.

**Comment by vogella** [comment]
i-build (daily build) can be found here: https://download.eclipse.org/eclipse/downloads/
