### ISSUE TITLE
org.eclipse.pde.ui.tests.classpathcontributor.ClasspathContributorTest fails in I-build

### ISSUE THREAD

**Issue by akurtakov** [eclipse-pde/eclipse.pde#243]
Failure can be seen at https://download.eclipse.org/eclipse/downloads/drops4/I20220727-1800/testresults/html/org.eclipse.pde.ui.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html and message is:
```
Unexpected classpath entry found: /home/jenkins/agent/workspace/ep425I-unit-cen64-gtk3-java11/workarea/I20220727-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.osgi.annotation.versioning_1.1.2.202109301733.jar[CPE_LIBRARY][K_BINARY][sourcePath:/home/jenkins/agent/workspace/ep425I-unit-cen64-gtk3-java11/workarea/I20220727-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.osgi.annotation.versioning_1.1.2.202109301733.jar][rootPath:/][isExported:false]

java.lang.AssertionError: Unexpected classpath entry found: /home/jenkins/agent/workspace/ep425I-unit-cen64-gtk3-java11/workarea/I20220727-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.osgi.annotation.versioning_1.1.2.202109301733.jar[CPE_LIBRARY][K_BINARY][sourcePath:/home/jenkins/agent/workspace/ep425I-unit-cen64-gtk3-java11/workarea/I20220727-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.osgi.annotation.versioning_1.1.2.202109301733.jar][rootPath:/][isExported:false]
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42) 
```

**Comment by laeubi** [comment]
I'll try to propose a fix, but the master build seem not to execute the test (or it is not failing there):
https://ci.eclipse.org/pde/job/eclipse.pde.ui/job/master/109/
