### ISSUE TITLE
org.eclipse.pde.api.tools.builder.tests.compatibility.BundleMergeSplitTests fails

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#261]
The org.eclipse.pde.api.tools.builder.tests.compatibility.BundleMergeSplitTests fails some times, it should either be fixed, disabled or explain why this particular test fails:

```
org.eclipse.core.runtime.CoreException: Component 'Test Plug-in' in the baseline 'workspace' is disposed
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.baselineDisposed(BundleComponent.java:1271)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.getBundleDescription(BundleComponent.java:992)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.createApiDescription(BundleComponent.java:390)
	at org.eclipse.pde.api.tools.internal.model.Component.getApiDescription(Component.java:106)
	at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.exportApiComponent(ApiBuilderTest.java:375)
	at org.eclipse.pde.api.tools.builder.tests.compatibility.BundleMergeSplitTests.setupTest(BundleMergeSplitTests.java:343)
	at org.eclipse.pde.api.tools.builder.tests.compatibility.BundleMergeSplitTests.test005(BundleMergeSplitTests.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
```

**Comment by vik-chand** [comment]
Also here https://download.eclipse.org/eclipse/downloads/drops4/I20221109-1850/testresults/html/org.eclipse.pde.api.tools.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by vik-chand** [comment]
I will look at this in 4.27 as this also occurs in nighty build. I will try to recreate on my local setup and see if I can do something about it.

**Comment by vik-chand** [comment]
Go from PDE
1 intermittent test failure is tracked by https://github.com/eclipse-pde/eclipse.pde/issues/261

**Comment by laeubi** [comment]
I have now further analyzed this and what the `BundleMergeSplitTests` do (and other probably do the same is the following:

1. They import all projects of the `referenceBaselineLocation`
2. Then a full build is performed and the API description file for all these projects is exported
3. Then a baseline is constructed from that and all projects gets deleted
4. Then the actual bundles to check are loaded and the test executes

This now can trigger a lot of background work, e.g. of course delete of project triggers events, new projects might change target state and so on what then of course has some chance to dispose the baseline while something is in progress.
