### ISSUE TITLE
org.eclipse.pde.ui.templates.tests.TestPDETemplates.validateProduct fails

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#262]
org.eclipse.pde.ui.templates.tests.TestPDETemplates.validateProduct currently fails on master, it should either be fixed, disabled or explain why this failure is related:

```
java.lang.AssertionError: 
Generated product fails validation: 
[Missing Constraint: Import-Package: org.apache.commons.io; version="1.3.1", Missing Constraint: Import-Package: org.apache.commons.io.output; version="1.3.1"]
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.pde.ui.templates.tests.TestPDETemplates.validateProduct(TestPDETemplates.java:193)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
```

**Comment by iloveeclipse** [comment]
Most likely regression from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/426

@mickaelistria : could you please check?

**Comment by akurtakov** [comment]
Mickal is on vacation, I'll take a look.
