### ISSUE TITLE
Frozen "Debug Configuration"

### ISSUE THREAD

**Issue by MLausberg** [eclipse-pde/eclipse.pde#274]
When opening the "Debug Configuration" and selecting any "Eclipse-Application" entry the UI freezes for some seconds. 

In Version 2022-06 it took 40s to initialize the dialog completly.
In Version 2022-09 it takes 4,9s to initialize the dialog completly.

I do see 
UI freeze of 4,9s
- Sample ... (1,1s)
- Sample ... (1,3s)
- Sample ... (2,0s)

eclipse.buildId=4.25.0.I20220809-0040
java.version=11.0.11
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui.monitoring
Info
Tue Aug 09 11:38:44 CEST 2022
Sample at 11:38:41.693 (+2,095s)
Thread 'main' tid=1 (RUNNABLE)

Stack Trace
	at java.base@11.0.11/java.io.RandomAccessFile.length(Native Method)
	at java.base@11.0.11/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1387)
	at java.base@11.0.11/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1483)
	at java.base@11.0.11/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)
	at java.base@11.0.11/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)
	at java.base@11.0.11/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base@11.0.11/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
	at java.base@11.0.11/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base@11.0.11/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at org.eclipse.pde.internal.core.TracingOptionsManager.getOptions(TracingOptionsManager.java:177)
	at org.eclipse.pde.internal.core.TracingOptionsManager.addToTemplate(TracingOptionsManager.java:55)
	at org.eclipse.pde.internal.core.TracingOptionsManager.createTemplate(TracingOptionsManager.java:49)
	at org.eclipse.pde.internal.core.TracingOptionsManager.getTracingTemplate(TracingOptionsManager.java:101)
	at org.eclipse.pde.internal.core.TracingOptionsManager.getTracingTemplateCopy(TracingOptionsManager.java:96)
	at org.eclipse.pde.internal.ui.launcher.TracingBlock.initializeFrom(TracingBlock.java:272)
	at org.eclipse.pde.ui.launcher.TracingTab.initializeFrom(TracingTab.java:81)
	at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfigurationTabGroup.lambda$0(AbstractPDELaunchConfigurationTabGroup.java:63)
	at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfigurationTabGroup$$Lambda$1326/0x0000000100f21040.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfigurationTabGroup.initializeFrom(AbstractPDELaunchConfigurationTabGroup.java:55)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:182)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:868)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.lambda$4(LaunchConfigurationTabGroupViewer.java:728)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer$$Lambda$1260/0x0000000100eae040.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:743)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:675)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:655)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:1049)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.lambda$1(LaunchConfigurationsDialog.java:612)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog$$Lambda$1255/0x0000000100eafc40.selectionChanged(Unknown Source)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$102/0x00000001002a7c40.run(Unknown Source)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1191)
	at org.eclipse.jface.viewers.StructuredViewer$$Lambda$561/0x0000000100797840.accept(Unknown Source)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:284)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:438)
	at org.eclipse.jface.util.OpenStrategy$1$$Lambda$1292/0x0000000100f08040.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1238)
	at org.eclipse.debug.ui.DebugUITools.lambda$1(DebugUITools.java:630)
	at org.eclipse.debug.ui.DebugUITools$$Lambda$1242/0x0000000100e85040.run(Unknown Source)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:636)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:574)
	at org.eclipse.debug.ui.actions.OpenLaunchDialogAction.run(OpenLaunchDialogAction.java:85)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$486/0x000000010069f840.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.ui.internal.Workbench$$Lambda$227/0x0000000100389c40.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at app//org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at app//org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at app//org.eclipse.equinox.launcher.Main.main(Main.java:1440)

**Comment by vogella** [comment]
@vik-chand @jukzi any idea how to make this faster? 4.9 seconds delay is much better than 40s but still very slow for the user.

**Comment by jukzi** [comment]
@MLausberg please add example workspace to reproduce or add sampling with VisualVm. How many plugins in workspace/target platform?

**Comment by MLausberg** [comment]
The Workspace currently has 526 different bundle (fragment/plugin/feature) and the bundle Java-Code is not Open-Source.
Because of this it is not possible to give you my exact workspace.


Attached you will find 2 *.jfr files created with "JDK Mission Control 8.2.0+runner"
[flight_recording.zip](https://github.com/eclipse-pde/eclipse.pde/files/9290437/flight_recording.zip)

I had to reproduce the behaviour with another Eclipse version, so here the Sample again:

eclipse.buildId=4.24.0.I20220607-0700
java.version=11.0.15
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.rcp.product

org.eclipse.ui.monitoring
Info
Tue Aug 09 14:31:36 CEST 2022
Sample at 14:31:33.114 (+2,692s)
Thread 'main' tid=1 (RUNNABLE)

Stack Trace
	at java.base@11.0.15/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base@11.0.15/java.lang.String.substring(String.java:1879)
	at org.eclipse.e4.ui.css.core.utils.ClassUtils.getPackageName(ClassUtils.java:47)
	at org.eclipse.e4.ui.css.swt.dom.WidgetElement.computeNamespaceURI(WidgetElement.java:180)
	at org.eclipse.e4.ui.css.swt.dom.WidgetElement.<init>(WidgetElement.java:140)
	at org.eclipse.e4.ui.css.swt.dom.ItemElement.<init>(ItemElement.java:27)
	at org.eclipse.e4.ui.css.swt.dom.SWTElementProvider.getElement(SWTElementProvider.java:101)
	at org.eclipse.e4.ui.css.core.impl.engine.RegistryCSSElementProvider.getElement(RegistryCSSElementProvider.java:55)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.getElement(AbstractCSSEngine.java:871)
	at org.eclipse.e4.ui.css.swt.engine.AbstractCSSSWTEngineImpl.getElement(AbstractCSSSWTEngineImpl.java:97)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:379)
	at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.applyStyles(AbstractCSSEngine.java:374)
	at org.eclipse.e4.ui.css.swt.engine.CSSSWTApplyStylesListener.lambda$0(CSSSWTApplyStylesListener.java:31)
	at org.eclipse.e4.ui.css.swt.engine.CSSSWTApplyStylesListener$$Lambda$425/0x0000000100713040.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Display.runSkin(Display.java:4146)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:211)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.jface.window.Window.getInitialSize(Window.java:590)
	at org.eclipse.jface.dialogs.Dialog.getInitialSize(Dialog.java:1202)
	at org.eclipse.jface.dialogs.TitleAreaDialog.getInitialSize(TitleAreaDialog.java:366)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.getInitialSize(LaunchConfigurationsDialog.java:1140)
	at org.eclipse.jface.window.Window.initializeBounds(Window.java:762)
	at org.eclipse.jface.dialogs.Dialog.initializeBounds(Dialog.java:721)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.initializeBounds(LaunchConfigurationsDialog.java:1133)
	at org.eclipse.jface.window.Window.create(Window.java:435)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.create(LaunchConfigurationsDialog.java:378)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1238)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.openLaunchConfigurationsDialog(DebugUIPlugin.java:774)
	at org.eclipse.debug.ui.actions.AbstractLaunchHistoryAction.runWithEvent(AbstractLaunchHistoryAction.java:415)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:229)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:218)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$522/0x00000001007ebc40.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.ui.internal.Workbench$$Lambda$303/0x00000001004e0c40.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.15/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.15/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.15/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at app//org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at app//org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by MLausberg** [comment]
and the corresponding VisualVM 2.1.4 result
[FrozenDebugConfiguration.zip](https://github.com/eclipse-pde/eclipse.pde/files/9290516/FrozenDebugConfiguration.zip)

**Comment by jukzi** [comment]
> and the corresponding VisualVM 2.1.4 result

that looks like WINDOWS performance problem / SWT.
![image](https://user-images.githubusercontent.com/51790620/183651948-8dfaef80-539a-4f46-bf47-e1228053adc3.png)

probably your virus scanner.

**Comment by MLausberg** [comment]
I agree.

the 40s delay cannot be reproduced yet.
If this is the case i will re-open the issue.
