### ISSUE TITLE
Product launch broken in latest I build - java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by Phillipus** [eclipse-pde/eclipse.pde#298]
Eclipse Build id: I20220816-1800
Windows 10
Java 11

1. Open `*.product` editor
2. Click "Launch an Eclipse application in Debug mode"
3. Target application does not launch
4. Exception is thrown

`
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.eclipse.pde.internal.ui.launcher.LaunchAction.concatArgs(LaunchAction.java:193)
	at org.eclipse.pde.internal.ui.launcher.LaunchAction.getVMArguments(LaunchAction.java:179)
	at org.eclipse.pde.internal.ui.launcher.LaunchAction.refreshConfiguration(LaunchAction.java:105)
	at org.eclipse.pde.internal.ui.launcher.LaunchAction.findLaunchConfiguration(LaunchAction.java:89)
	at org.eclipse.pde.internal.ui.launcher.LaunchAction.run(LaunchAction.java:69)
	at org.eclipse.pde.ui.launcher.EclipseLaunchShortcut.launch(EclipseLaunchShortcut.java:84)
	at org.eclipse.pde.internal.ui.editor.PDELauncherFormEditor.launch(PDELauncherFormEditor.java:125)
	at org.eclipse.pde.internal.ui.editor.LaunchShortcutOverviewPage.linkActivated(LaunchShortcutOverviewPage.java:60)
	at org.eclipse.pde.internal.ui.editor.product.OverviewPage.linkActivated(OverviewPage.java:105)
	at org.eclipse.ui.forms.widgets.FormText.activateLink(FormText.java:1546)
	at org.eclipse.ui.forms.widgets.FormText.handleMouseClick(FormText.java:1357)
	at org.eclipse.ui.forms.widgets.FormText$2.mouseUp(FormText.java:440)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
`

**Comment by Phillipus** [comment]
If I remove the VM arguments from the product file it launches.

Product file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?pde version="3.5"?>

<product name="Archi" uid="com.archimatetool.editor.product" id="com.archimatetool.editor.product" application="com.archimatetool.editor.app" version="4.10.0.qualifier" useFeatures="true" includeLaunchers="true">

   <configIni use="">
   </configIni>

   <launcherArgs>
      <vmArgs>-Dshowheap=true
-Dnashorn.args=--no-deprecation-warning
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
      </vmArgs>
      <vmArgsLin>-Dosgi.instance.area=@user.home/.archi4
      </vmArgsLin>
      <vmArgsMac>-Dosgi.instance.area=&quot;@user.home/Library/Application Support/Archi4&quot;
-XstartOnFirstThread
-Xdock:icon=../Resources/icon.icns
      </vmArgsMac>
      <vmArgsWin>-Dosgi.instance.area=@user.home/AppData/Roaming/Archi4
      </vmArgsWin>
   </launcherArgs>

   <windowImages i16="/com.archimatetool.editor/img/app-16.png" i32="/com.archimatetool.editor/img/app-32.png" i48="/com.archimatetool.editor/img/app-48.png" i64="/com.archimatetool.editor/img/app-64.png" i128="/com.archimatetool.editor/img/app-128.png" i256="/com.archimatetool.editor/img/app-256.png"/>

   <splash
      location="com.archimatetool.editor" />
   <launcher name="Archi">
      <linux icon="/com.archimatetool.editor.product/icons/icon.xpm"/>
      <macosx icon="/com.archimatetool.editor.product/icons/icon.icns"/>
      <win useIco="true">
         <ico path="/com.archimatetool.editor.product/icons/icon.ico"/>
         <bmp/>
      </win>
   </launcher>

   <vm>
   </vm>

   <plugins>
   </plugins>

   <features>
      <feature id="com.archimatetool.eclipse.feature"/>
      <feature id="com.archimatetool.editor.feature"/>
      <feature id="com.archimatetool.gef.feature"/>
      <feature id="org.eclipse.emf.ecore"/>
      <feature id="org.eclipse.emf.common"/>
      <feature id="org.eclipse.help"/>
      <feature id="org.eclipse.rcp"/>
      <feature id="org.eclipse.e4.rcp"/>
      <feature id="org.eclipse.equinox.p2.core.feature"/>
      <feature id="org.eclipse.ecf.core.feature"/>
      <feature id="org.eclipse.ecf.filetransfer.feature"/>
      <feature id="org.eclipse.ecf.filetransfer.ssl.feature"/>
      <feature id="org.eclipse.ecf.core.ssl.feature"/>
      <feature id="org.eclipse.equinox.p2.extras.feature"/>
      <feature id="org.eclipse.ecf.filetransfer.httpclient5.feature"/>
      <feature id="com.archimatetool.script.feature"/>
      <feature id="org.archicontribs.modelrepository.feature"/>
      <feature id="com.archimatetool.vista.feature"/>
      <feature id="com.archimatetool.excel.feature"/>
   </features>

   <configurations>
      <plugin id="org.apache.felix.scr" autoStart="true" startLevel="2" />
      <plugin id="org.eclipse.core.runtime" autoStart="true" startLevel="0" />
      <plugin id="org.eclipse.equinox.common" autoStart="true" startLevel="2" />
      <plugin id="org.eclipse.equinox.event" autoStart="true" startLevel="2" />
      <plugin id="org.eclipse.equinox.p2.reconciler.dropins" autoStart="true" startLevel="0" />
      <plugin id="org.eclipse.equinox.simpleconfigurator" autoStart="true" startLevel="1" />
   </configurations>

   <preferencesInfo>
      <targetfile overwrite="false"/>
   </preferencesInfo>

   <cssInfo>
   </cssInfo>

</product>
```

**Comment by merks** [comment]
@HannesWell The code at line 193 trying to add to a list created by `Arrays.asList` at line 186:

https://github.com/eclipse-pde/eclipse.pde/blob/065da8c7a25bad5469981ae9dc948dbffdc5ef02/ui/org.eclipse.pde.ui/src/org/eclipse/pde/internal/ui/launcher/LaunchAction.java#L185-L204

**Comment by merks** [comment]
This change:

https://github.com/eclipse-pde/eclipse.pde/commit/79ed2805d6a85fd1f46b5d2ef406c12ceaad7b52#diff-4b6639780456e0319239ce242173518757a5265789cfa529c1e50274eb15a3b3R193

**Comment by merks** [comment]
I think a simple fix would be to change line 186 to this:
```
	private String concatArgs(String initialArgs, String userArgs) {
		List<String> arguments = new ArrayList<>(Arrays.asList(DebugPlugin.splitArguments(initialArgs)));
```

**Comment by merks** [comment]
I can create a PR for that if others think that's a good fix...

**Comment by Phillipus** [comment]
Thanks, Ed, for your `super-super-fast` response. 🚀 

Using a mutable list rather than an immutable list seems to me the correct fix.

**Comment by merks** [comment]
This is fixed in time for M3.

**Comment by akurtakov** [comment]
Thanks Ed for the fast fix!

**Comment by Phillipus** [comment]
@merks Many thanks! I'll test when the next I build is done.

**Comment by Phillipus** [comment]
Tested in `I20220817-1800` and working. Thanks again.
