### ISSUE TITLE
An internal error occurred during: "Resolving "zak3" target definition". Cannot invoke "org.eclipse.equinox.internal.p2.engine.ProfileLock.unlock()" because "lock" is null

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#310]
Maybe a p2 problem, but I frequently see the following error:

![image](https://user-images.githubusercontent.com/139910/186616563-3831c1be-b896-4ec8-a047-af92d9c79aeb.png)

java.lang.IllegalStateException: The profile is not locked.
	at org.eclipse.equinox.internal.p2.engine.ProfileLock.unlock(ProfileLock.java:126)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.internalUnlockProfile(SimpleProfileRegistry.java:952)
	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.removeProfile(SimpleProfileRegistry.java:472)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.deleteProfileWithId(P2TargetUtils.java:276)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.deleteProfile(P2TargetUtils.java:267)
	at org.eclipse.pde.internal.ui.editor.targetdefinition.TargetEditor$TargetChangedListener$1.run(TargetEditor.java:602)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

If the profile is not locked, I guess we should not see an error. It might be a p2 issue and if that is the case, we should tranfer it to p2.

WDYT @merks?

**Comment by mickaelistria** [comment]
Is this a regression compared to 4.24 ?

**Comment by vogella** [comment]
Nothing we need to fix for 4.25 a restart of Eclipse fixes this and it does not happen all the time.

**Comment by merks** [comment]
Unless we can reproduce it we can't determine the cause or fix anything anywhere.  The earlier call that locks the profile doesn't actually check whether the lock succeeds but continues and then calls unlock which fails if the thing isn't locked.  Seems kind of strange, but the question remains, why couldn't it lock?  What strange state are things in?

**Comment by vogella** [comment]
How to reproduce:

Create the following file:

````

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/eclipse/updates/4.28-I-builds"/>
			<unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
			<unit id="org.eclipse.platform.sdk" version="0.0.0"/>
		</location>
	
		
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/justj/jres/17/updates/release"/>
			<unit id="org.eclipse.justj.openjdk.hotspot.jre.minimal.feature.group" version="0.0.0"/>
		</location>
		<location includeDependencyDepth="infinite" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>com.google.code.gson</groupId>
					<artifactId>gson</artifactId>
					<version>2.8.6</version>
					<type>jar</type>
				</dependency>
			</dependencies>
		</location>
	</locations>
</target>
````

Activate. While the target file is downloading (@merks you may want to use a slower network for in case you are testing this), change  "4.28-I-builds" to "latest" and re-activate. ---> Errors in the log and in multiple cases a lock which requires reboot.
