### ISSUE TITLE
NPE in ClasspathHelper.getDevPaths()

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#321]
randomly happened : 
eclipse.buildId=4.23.0.I20220308-0310
```
java.lang.NullPointerException
    at org.eclipse.pde.internal.core.ClasspathHelper.getDevPaths(ClasspathHelper.java:284)
    at org.eclipse.pde.internal.core.ClasspathHelper.getDevEntriesProperties(ClasspathHelper.java:117)
    at org.eclipse.pde.internal.core.ClasspathHelper.getDevEntriesProperties(ClasspathHelper.java:83)
    at org.eclipse.pde.launching.EclipseApplicationLaunchConfiguration.getProgramArguments(EclipseApplicationLaunchConfiguration.java:98)
    at org.eclipse.pde.launching.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:127)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
after restarting eclipse the error was gone.

was already reported in https://bugs.eclipse.org/bugs/show_bug.cgi?id=437727

=> model.getPluginBase().getLibraries() returned a null element in the array

It's unclear how that can happen but it might help to make eager null checks at add(IPluginLibrary library) methods before adding to the list - to get the root reason somewhen.

**Comment by jukzi** [comment]
The error could also happen if two launch configurations started at the same time.
org.eclipse.pde.internal.core.bundle.BundlePluginBase.getLibraries() is called in parallel, initializing BundlePluginBase.libraries with a non thread safe ArrayList and then adding elements. two add in parallel to an ArrayList can lead to an null element.

**Comment by jukzi** [comment]
not planned to fix
