### ISSUE TITLE
ConcurrentModificationException in BundleSourcePage / Bundle.fDocumentHeaders

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#329]
Bundle.fDocumentHeaders is not a concurrent datastructure and access not synchronized 

```
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
	at java.base/java.util.TreeMap$ValueIterator.next(TreeMap.java:1253)
	at org.eclipse.pde.internal.ui.editor.plugin.BundleSourcePage.getRangeElement(BundleSourcePage.java:285)
	at org.eclipse.pde.internal.ui.editor.PDESourcePage.handleSelectionChangedSourcePage(PDESourcePage.java:516)
	at org.eclipse.pde.internal.ui.editor.plugin.BundleSourcePage.handleSelectionChangedSourcePage(BundleSourcePage.java:651)
	at org.eclipse.pde.internal.ui.editor.PDESourcePage$PDESourcePageChangedListener.selectionChanged(PDESourcePage.java:92)
	at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2714)
	at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2644)
	at org.eclipse.jface.text.TextViewer$2.run(TextViewer.java:2623)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4158)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3262)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

eclipse.buildId=4.23.0.I20220308-0310
java.version=11.0.14
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data C:\wamas\workspace\w5_15-staging_IDE-target

**Comment by jukzi** [comment]
and again:
```
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
	at java.base/java.util.TreeMap$ValueIterator.next(TreeMap.java:1253)
	at org.eclipse.pde.internal.ui.editor.plugin.BundleSourcePage.getRangeElement(BundleSourcePage.java:284)
	at org.eclipse.pde.internal.ui.editor.PDESourcePage.handleSelectionChangedSourcePage(PDESourcePage.java:516)
	at org.eclipse.pde.internal.ui.editor.plugin.BundleSourcePage.handleSelectionChangedSourcePage(BundleSourcePage.java:649)
	at org.eclipse.pde.internal.ui.editor.PDESourcePage$PDESourcePageChangedListener.selectionChanged(PDESourcePage.java:92)
	at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2718)
	at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2648)
	at org.eclipse.jface.text.TextViewer$2.run(TextViewer.java:2627)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4166)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3275)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

eclipse.buildId=4.24.0.I20220607-0700
java.version=11.0.16
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.sdk.ide
Command-line arguments:  -product org.eclipse.sdk.ide -data C:\wamas\workspace\w5_15-staging_IDE-target -dev file:C:/wamas/workspace/w5_15-staging_IDE/.metadata/.plugins/org.eclipse.pde.core/W5-REAL-WS/dev.properties -os win32 -ws win32 -arch x86_64


Happend while editing a lot MANIFEST.MF
