### ISSUE TITLE
144 errors after JDT merge in I20220921-0710

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#341]
See 
https://download.eclipse.org/eclipse/downloads/drops4/I20220921-0710/testResults.php
and especially
https://download.eclipse.org/eclipse/downloads/drops4/I20220921-0710/testresults/html/org.eclipse.pde.build.tests_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
most of them are  like
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.launching.environments.IExecutionEnvironment.getDefaultVM()" because "environment" is null
at org.eclipse.pde.internal.build.site.PDEState.bestVmInstallFor(PDEState.java:495)
at org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(PDEState.java:466)
at org.eclipse.pde.internal.build.site.PDEState.resolveState(PDEState.java:443)
at org.eclipse.pde.internal.build.site.BuildTimeSite.getRegistry(BuildTimeSite.java:134)
at org.eclipse.pde.internal.build.builder.BuildDirector.computeElements(BuildDirector.java:126)
at org.eclipse.pde.internal.build.builder.BuildDirector.generateChildrenScripts(BuildDirector.java:284)
at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:230)
at org.eclipse.pde.internal.build.builder.BuildDirector.generateIncludedFeatureBuildFile(BuildDirector.java:268)
at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:228)
at org.eclipse.pde.internal.build.builder.BuildDirector.generate(BuildDirector.java:223)
at org.eclipse.pde.internal.build.BuildScriptGenerator.generateFeatures(BuildScriptGenerator.java:253)
at org.eclipse.pde.internal.build.BuildScriptGenerator.generate(BuildScriptGenerator.java:130)
at org.eclipse.pde.internal.build.tasks.BuildScriptGeneratorTask.run(BuildScriptGeneratorTask.java:110)
at org.eclipse.pde.internal.build.tasks.BuildScriptGeneratorTask.execute(BuildScriptGeneratorTask.java:96)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
```

**Comment by vik-chand** [comment]
I think it is because jdt.debug Java 19 merge to master is missing. This should get corrected in the I build containing this merge.

**Comment by iloveeclipse** [comment]
@SarikaSinha : I saw you've just merged jdt debug and Noopur did that for jdt.ui.
Are we ready with outstanding merges now?
If yes, I would like to trigger new I Build to see which regressions are left.

**Comment by jukzi** [comment]
@HannesWell regarding 
https://github.com/eclipse-pde/eclipse.pde/issues/194
even though an JDK19 environment would probably fix the issue, it is documented that JavaRuntime.getExecutionEnvironmentsManager().getEnvironment(execEnvID) may return null and in that case org.eclipse.pde.internal.build.site.PDEState.bestVmInstallFor(IExecutionEnvironment) could just return null too.

**Comment by SarikaSinha** [comment]
> @SarikaSinha : I saw you've just merged jdt debug and Noopur did that for jdt.ui. Are we ready with outstanding merges now? If yes, I would like to trigger new I Build to see which regressions are left.

We are working on adjusting the bundle versions in UI and debug. Will trigger after that.

**Comment by vik-chand** [comment]
Resolved after jdt.debug and jdt.ui merge

**Comment by SarikaSinha** [comment]
I build has been triggered.

**Comment by vik-chand** [comment]
verified in https://download.eclipse.org/eclipse/downloads/drops4/I20220922-0520/testResults.php

**Comment by jukzi** [comment]
> That's right. Do you plan to provide a PR to fix that?

https://github.com/eclipse-pde/eclipse.pde/pull/342
