### ISSUE TITLE
Intermittent test failures in API tools

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#345]
org.eclipse.pde.api.tools.builder.tests.compatibility.ProjectTypeContainerTests	testPackageNames	Error	Component 'API Tools Tests Plug-in A' in the baseline 'workspace' is disposed

org.eclipse.core.runtime.CoreException: Component 'API Tools Tests Plug-in A' in the baseline 'workspace' is disposed
at org.eclipse.pde.api.tools.internal.model.BundleComponent.baselineDisposed(BundleComponent.java:1271)
at org.eclipse.pde.api.tools.internal.model.BundleComponent.getBundleDescription(BundleComponent.java:992)
at org.eclipse.pde.api.tools.internal.model.BundleComponent.createApiDescription(BundleComponent.java:390)
at org.eclipse.pde.api.tools.internal.model.Component.getApiDescription(Component.java:106)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.exportApiComponent(ApiBuilderTest.java:375)
at org.eclipse.pde.api.tools.builder.tests.compatibility.CompatibilityTest.setUp(CompatibilityTest.java:161)
at junit.framework.TestCase.runBare(TestCase.java:140)
at junit.framework.TestResult$1.protect(TestResult.java:122) 

These are the failing test cases with similar stack

ProjectTypeContainerTests::testPackageNames
BundleVersionTests::test005
BundleMergeSplitTests::test007
BundleMergeSplitTests::test003

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-pde/eclipse.pde/issues/553
