### ISSUE TITLE
Exception while merging MANIFEST.MF

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#364]
While git is merging MANIFEST it changes MANIFEST into a non readable format which results in logged error:
```
org.osgi.framework.BundleException: The manifest line "<<<<<<< HEADcom.myplugin" is invalid; it has no colon ':' character after the header key.
	at org.eclipse.osgi.util.ManifestElement.parseBundleManifest(ManifestElement.java:527)
	at org.eclipse.pde.internal.core.bundle.BundleModel.load(BundleModel.java:70)
	at org.eclipse.pde.internal.core.bundle.BundleModel.reload(BundleModel.java:145)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.loadModel(WorkspaceModelManager.java:331)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.handleBundleManifestDelta(WorkspacePluginModelManager.java:353)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.handleFileDelta(WorkspacePluginModelManager.java:190)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.visit(WorkspaceModelManager.java:215)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.handleResourceDelta(WorkspaceModelManager.java:180)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(WorkspaceModelManager.java:168)
	at org.eclipse.jdt.internal.core.DeltaProcessingState$1.run(DeltaProcessingState.java:496)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:489)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1514)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:50)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
eclipse.buildId=4.24.0.I20220607-0700
maybe it could fail more silently?

**Comment by preveen-stack** [comment]
What would you recommend in this scenario? include the offending line in the error message and then continue parsing the file?

**Comment by jukzi** [comment]
For exactly that scenario (a typical usecase) i expect no error message logged at all. An error marker in the Manifest (optimal at the offending line) while that state persists would be enough.

**Comment by laeubi** [comment]
I would assume (from past experience in that area) that it is simply not expected/handled here and just bubble up the chain until it is logged by the default handler.

**Comment by preveen-stack** [comment]
In view of the comment by @laeubi Can you  (@jukzi ) elaborate a bit more on the use case.

the line 
> "<<<<<<< HEADcom.myplugin" 

looks like left there by a git merge process for manual intervention and as such the MANIFEST file seems to be not final.

**Comment by jukzi** [comment]
exactly. modify a MANIFEST.MF with a merge conflict and merge it

**Comment by preveen-stack** [comment]
I get the point @jukzi. 

Guess we should do a best effort to parse the MANIFEST file ignoring issues if possible in parsing.

 @laeubi would you mind giving further insight into your previous experience in the area why you feel that we should bubble this up the chain.
