### ISSUE TITLE
NPE when exporting plug-ins via the export wizard

### ISSUE THREAD

**Issue by pzi-dsa** [eclipse-pde/eclipse.pde#366]
m2e introduces the functionality to automatically generate Eclipse features from pom-dependencies.

When this synthetic feature is in the class path, it is no longer possible to export plugins, due to a NullPointerException being thrown.
The main cause seems to be that the install location of those features is always set to null. Given that this is a valid return type, I think this is an Eclipse bug, rather than an m2e bug.

I think it would be sufficient to simply add a null check in the FeatureExportOperation in order to exclude those artifacts.

Steps to reproduce:
1) Set a target platform definition containing batik-all as your active target platform.
GAV:
```
<dependency>
    <groupId>org.apache.xmlgraphics</groupId>
    <artifactId>batik-all</artifactId>
    <version>1.14</version>
    <type>pom</type>
</dependency>
```

2) Create a blank plugin

3) Export the plugin via the export wizard. Export -> Plug-in Development -> Deployable plug-ins and fragments

This fails with the following exception:
```
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at org.eclipse.pde.internal.build.site.BuildTimeSiteFactory.findFeatureXMLs(BuildTimeSiteFactory.java:175)
	at org.eclipse.pde.internal.build.site.BuildTimeSiteFactory.createSite(BuildTimeSiteFactory.java:64)
	at org.eclipse.pde.internal.build.AbstractScriptGenerator.getSite(AbstractScriptGenerator.java:313)
	at org.eclipse.pde.internal.build.BuildScriptGenerator.generate(BuildScriptGenerator.java:123)
	at org.eclipse.pde.internal.core.exports.FeatureExportOperation.doExport(FeatureExportOperation.java:305)
	at org.eclipse.pde.internal.core.exports.FeatureBasedExportOperation.run(FeatureBasedExportOperation.java:62)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Alternatively, you can also just import the following artifacts into your workspace:
[Workspace.zip](https://github.com/eclipse-pde/eclipse.pde/files/9819045/Workspace.zip)

**Comment by pzi-dsa** [comment]
Fixed with #367.
I've tried the latest integration build (I20221103-0530) and the problem no longer shows up.
