### ISSUE TITLE
An internal error occurred during: "Export Plug-ins".

### ISSUE THREAD

**Issue by MLausberg** [eclipse-pde/eclipse.pde#372]
Eclipse IDE for RCP and RAP Developers (includes Incubating components)

Version: 2022-09 (4.25.0)
Build id: 20220908-1902

![image](https://user-images.githubusercontent.com/40763331/198508382-2dc53812-446d-4f1a-bf0f-bb733ace9724.png)

![image](https://user-images.githubusercontent.com/40763331/198508832-7030d417-97b0-4133-a53d-2bebdf89e51d.png)

![image](https://user-images.githubusercontent.com/40763331/198508645-4201f826-7ed7-46bb-b498-e10ae30f64e8.png)

Exception Stack Trace:
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at org.eclipse.pde.internal.build.site.BuildTimeSiteFactory.findFeatureXMLs(BuildTimeSiteFactory.java:175)
	at org.eclipse.pde.internal.build.site.BuildTimeSiteFactory.createSite(BuildTimeSiteFactory.java:64)
	at org.eclipse.pde.internal.build.AbstractScriptGenerator.getSite(AbstractScriptGenerator.java:313)
	at org.eclipse.pde.internal.build.BuildScriptGenerator.generate(BuildScriptGenerator.java:123)
	at org.eclipse.pde.internal.core.exports.FeatureExportOperation.doExport(FeatureExportOperation.java:305)
	at org.eclipse.pde.internal.core.exports.FeatureBasedExportOperation.run(FeatureBasedExportOperation.java:62)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by laeubi** [comment]
Might be related to:
- https://github.com/eclipse-pde/eclipse.pde/pull/367

**Comment by vogella** [comment]
@MLausberg please check with @pzi-dsa https://github.com/eclipse-pde/eclipse.pde/pull/367 should fix your issue also. You can try with the latest I-build from example with https://download.eclipse.org/eclipse/downloads/drops4/I20221107-1920/
