### ISSUE TITLE
FeatureBasedLaunchTest::testGetMergedBundleMap_requiredFeatureWithSpecificVersion1 failed on 1 platform

### ISSUE THREAD

**Issue by vik-chand** [eclipse-pde/eclipse.pde#398]
The failure trace is as below in I20221109-1850

	[pluginResolution explicit workspace] expected: { plugin.a.w.110-1.0.0(e)="default:default" } but was: { plugin.a.w.100-1.0.0(e)="default:default" }

org.opentest4j.AssertionFailedError: [pluginResolution explicit workspace]
expected:
{
plugin.a.w.110-1.0.0(e)="default:default"
}
but was:
{
plugin.a.w.100-1.0.0(e)="default:default"
}
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at org.eclipse.pde.ui.tests.launcher.AbstractLaunchTest.assertPluginMapsEquals(AbstractLaunchTest.java:127)
at org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest.assertGetMergedBundleMap(FeatureBasedLaunchTest.java:1439)
at org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest.assertGetMergedBundleMap(FeatureBasedLaunchTest.java:1417)
at org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest.testGetMergedBundleMap_requiredFeatureWithSpecificVersion1(FeatureBasedLaunchTest.java:939)
at java.base/jdk.internal.refle

**Comment by HannesWell** [comment]
The test does not fail anymore.
