### ISSUE TITLE
M2E error 2022-12 M3+RC1 - Maven - Update Maven configuration fails due to java.lang.NullPointerException

### ISSUE THREAD

**Issue by minduch** [eclipse-pde/eclipse.pde#414]
In Eclipse 2022-12 M3 and RC1, selecting the menu item `Maven - Update Project...` causes multiple NullPointerExceptions as shown below.

The installation uses the "M2E - Complete Development Kit 2.1.0.20221118-1906". It behaves the same way on Windows 11 and on macOS x86_64 as well as macOS Aarch64 with the same type of configuration.

We use Tycho 3.0.0 in the "pom.xml" files for our plugin development, product, etc.

Dialog box "Multiple Problems have occurred" is shown with "Updating Maven Project" lines in a list, details as follows:

```
Unable to update Maven configuration
Could not update project com.iizix.stress configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizix.txp configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizix.app.builder configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizigo.run configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizix.test configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizix.server.loadbalancer configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizix.db configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
Could not update project com.iizix.term configuration
Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
```

I have not seen this problem in Eclipse 2022-12 M2, M1 or 2022-09 or earlier.

The error log shows multiple "identical" entries for the `org.eclipse.m2d.core` plugin such as:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.core.build.IBuildEntry.getTokens()" because "entry" is null
	at org.eclipse.m2e.pde.connector.PDEProjectHelper.getDefaultLibraryOutputFolder(PDEProjectHelper.java:140)
	at org.eclipse.m2e.pde.connector.PDEProjectHelper.getOutputLocation(PDEProjectHelper.java:120)
	at org.eclipse.m2e.pde.connector.PDEProjectHelper.configurePDEBundleProject(PDEProjectHelper.java:91)
	at org.eclipse.m2e.pde.connector.TychoPackagingsConfigurator.configure(TychoPackagingsConfigurator.java:50)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:123)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:494)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:488)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:416)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:410)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1070)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by merks** [comment]
I think this should be reported here:

https://github.com/eclipse-m2e/m2e-core

Sorry we can't move the issue between organizations.

**Comment by HannesWell** [comment]
Fixed that already in https://github.com/eclipse-m2e/m2e-core/pull/1068.
This fix is contained in the latest M2E release at https://download.eclipse.org/technology/m2e/releases/2.1.0/
and will be included in the Eclipse 2022-12 RC2

**Comment by minduch** [comment]
Just to let you know that adding that repo and performing Check for Updates made it work again. Many thanks.

**Comment by HannesWell** [comment]
You are welcome and thanks for the Feedback. :)
