### ISSUE TITLE
Using SNAPSHOT in version cause java.lang.IllegalArgumentException: invalid version "${​​parsedVersion.osgiVersion}​​": non-numeric "${​​parsedVersion"

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#440]
We have a bundle using the following header:
````
Bundle-Version: 2.0.0.SNAPSHOT
`````

We see the following exception in the PDE log, AFAIK the version above it correct and created by Tycho.

    java.lang.IllegalArgumentException: invalid version "${​​parsedVersion.osgiVersion}​​": non-numeric "${​​parsedVersion"
    at org.osgi.framework.Version.parseInt(Version.java:169)
    at org.osgi.framework.Version.<init>(Version.java:126)
    at org.eclipse.pde.internal.core.BundleManifestSourceLocationManager.setPlugins(BundleManifestSourceLocationManager.java:220)
    at org.eclipse.pde.internal.core.SourceLocationManager.initializeBundleManifestLocations(SourceLocationManager.java:443)
    at org.eclipse.pde.internal.core.SourceLocationManager.getBundleManifestLocator(SourceLocationManager.java:252)
    at org.eclipse.pde.internal.core.SourceLocationManager.getBundleManifestLocation(SourceLocationManager.java:244)
    at org.eclipse.pde.internal.core.SourceLocationManager.searchBundleManifestLocations(SourceLocationManager.java:332)
    at org.eclipse.pde.internal.core.SourceLocationManager.findSourcePath(SourceLocationManager.java:83)
    at org.eclipse.pde.internal.core.ClasspathUtilCore.getSourceAnnotation(ClasspathUtilCore.java:193)
    at org.eclipse.pde.internal.core.ClasspathUtilCore.getSourceAnnotation(ClasspathUtilCore.java:184)
    at org.eclipse.pde.internal.core.ClasspathUtilCore$ClasspathLibrary.findSourcePath(ClasspathUtilCore.java:279)
    at org.eclipse.pde.internal.core.ClasspathUtilCore$ClasspathLibrary.createClasspathEntry(ClasspathUtilCore.java:273)
    at org.eclipse.pde.internal.core.ClasspathUtilCore.addLibraries(ClasspathUtilCore.java:50)
    at org.eclipse.pde.internal.core.SearchablePluginsManager.computeContainerClasspathEntries(SearchablePluginsManager.java:203)
    at org.eclipse.pde.internal.core.ExternalJavaSearchClasspathContainer.getClasspathEntries(ExternalJavaSearchClasspathContainer.java:29)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3277)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3435)
    at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2520)
    at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4632)
    at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:39)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NumberFormatException: For input string: "${​​parsedVersion"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.base/java.lang.Integer.parseInt(Integer.java:654)
    at java.base/java.lang.Integer.parseInt(Integer.java:786)
    at org.osgi.framework.Version.parseInt(Version.java:167)
    ... 20 more

**Comment by merks** [comment]
I assume the string `${​​parsedVersion.osgiVersion}​​` that it doesn't like (and is definitely not correct) is coming from somewhere.  Have you searched for it?

**Comment by vogella** [comment]
Thanks, I looked at the wrong file. Indeed the source bundle contains a wrong entry. Not an PDE issue in this case.

Sorry for the noise.

**Comment by HannesWell** [comment]
> Thanks, I looked at the wrong file. Indeed the source bundle contains a wrong entry. Not an PDE issue in this case.

That's probably coming from Maven, i.e. https://www.mojohaus.org/build-helper-maven-plugin/parse-version-mojo.html
