### ISSUE TITLE
Launching JUnit Plug-In tests failes in 2022-12

### ISSUE THREAD

**Issue by guw** [eclipse-pde/eclipse.pde#505]
I'm unable to run any JUnit 5 plug-in test.
```
!ENTRY org.eclipse.osgi 4 0 2023-03-14 07:15:25.359
!MESSAGE Application error
!STACK 1
java.lang.IllegalArgumentException: Bundle "org.eclipse.jdt.junit5.runtime" not found. Possible causes include missing dependencies, too restrictive version ranges, or a non-matching required execution environment.
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.getClassLoader(RemotePluginTestRunner.java:123)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.readPluginArgs(RemotePluginTestRunner.java:173)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.init(RemotePluginTestRunner.java:130)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:67)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:53)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:36)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

I see the following in the log file:

```
!ENTRY org.eclipse.jdt.junit5.runtime 2 0 2023-03-14 07:15:25.354
!MESSAGE Could not resolve module: org.eclipse.jdt.junit5.runtime [345]
  Unresolved requirement: Require-Bundle: junit-jupiter-migrationsupport; bundle-version="5.4.0"
    -> Bundle-SymbolicName: junit-jupiter-migrationsupport; bundle-version="5.9.2"
       junit-jupiter-migrationsupport [73]
  Unresolved requirement: Require-Bundle: junit-vintage-engine; bundle-version="5.4.0"
    -> Bundle-SymbolicName: junit-vintage-engine; bundle-version="5.9.2"
       junit-vintage-engine [82]
         No resolution report for the bundle.  Unresolved requirement: Require-Bundle: junit-platform-suite-commons; bundle-version="1.8.1"
    -> Bundle-SymbolicName: junit-platform-suite-commons; bundle-version="1.9.2"
       junit-platform-suite-commons [80]
         Unresolved requirement: Import-Package: org.junit.platform.suite.api; version="[1.9.0,2.0.0)"
           -> Export-Package: org.junit.platform.suite.api; bundle-symbolic-name="junit-platform-suite-api"; bundle-version="1.9.2"; version="1.9.2"; status="MAINTAINED"; uses:="org.apiguardian.api,org.junit.platform.commons.annotation"
              junit-platform-suite-api [79]
                No resolution report for the bundle.  Unresolved requirement: Require-Bundle: junit-platform-suite-engine; bundle-version="1.8.1"
    -> Bundle-SymbolicName: junit-platform-suite-engine; bundle-version="1.9.2"
       junit-platform-suite-engine [81]
         Unresolved requirement: Import-Package: org.junit.platform.suite.commons; version="[1.9.0,2.0.0)"; status="INTERNAL"
           -> Export-Package: org.junit.platform.suite.commons; bundle-symbolic-name="junit-platform-suite-commons"; bundle-version="1.9.2"; version="1.9.2"; status="INTERNAL"; mandatory:="status"; uses:="org.apiguardian.api,org.junit.platform.engine,org.junit.platform.launcher"
         Unresolved requirement: Import-Package: org.junit.platform.suite.api; version="[1.9.0,2.0.0)"
           -> Export-Package: org.junit.platform.suite.api; bundle-symbolic-name="junit-platform-suite-api"; bundle-version="1.9.2"; version="1.9.2"; status="MAINTAINED"; uses:="org.apiguardian.api,org.junit.platform.commons.annotation"
  Unresolved requirement: Require-Bundle: junit-platform-runner; bundle-version="1.4.0"
    -> Bundle-SymbolicName: junit-platform-runner; bundle-version="1.9.2"
       junit-platform-runner [78]
         Unresolved requirement: Import-Package: org.junit.platform.suite.commons; version="[1.9.0,2.0.0)"; status="INTERNAL"
           -> Export-Package: org.junit.platform.suite.commons; bundle-symbolic-name="junit-platform-suite-commons"; bundle-version="1.9.2"; version="1.9.2"; status="INTERNAL"; mandatory:="status"; uses:="org.apiguardian.api,org.junit.platform.engine,org.junit.platform.launcher"
         Unresolved requirement: Import-Package: org.junit.platform.suite.api; version="[1.9.0,2.0.0)"
           -> Export-Package: org.junit.platform.suite.api; bundle-symbolic-name="junit-platform-suite-api"; bundle-version="1.9.2"; version="1.9.2"; status="MAINTAINED"; uses:="org.apiguardian.api,org.junit.platform.commons.annotation"
  Unresolved requirement: Require-Bundle: junit-platform-suite-api; bundle-version="1.4.0"
    -> Bundle-SymbolicName: junit-platform-suite-api; bundle-version="1.9.2"
  Unresolved requirement: Require-Bundle: junit-jupiter-params; bundle-version="5.4.0"
    -> Bundle-SymbolicName: junit-jupiter-params; bundle-version="5.9.2"
       junit-jupiter-params [74]
         Unresolved requirement: Import-Package: kotlin; resolution:="optional"
         Unresolved requirement: Import-Package: kotlin.jvm.internal; resolution:="optional"
```
and
```
!ENTRY junit-platform-suite-engine 2 0 2023-03-14 07:15:25.356
!MESSAGE Could not resolve module: junit-platform-suite-engine [81]
  Unresolved requirement: Import-Package: org.junit.platform.suite.commons; version="[1.9.0,2.0.0)"; status="INTERNAL"
    -> Export-Package: org.junit.platform.suite.commons; bundle-symbolic-name="junit-platform-suite-commons"; bundle-version="1.9.2"; version="1.9.2"; status="INTERNAL"; mandatory:="status"; uses:="org.apiguardian.api,org.junit.platform.engine,org.junit.platform.launcher"
       junit-platform-suite-commons [80]
         Unresolved requirement: Import-Package: org.junit.platform.suite.api; version="[1.9.0,2.0.0)"
           -> Export-Package: org.junit.platform.suite.api; bundle-symbolic-name="junit-platform-suite-api"; bundle-version="1.9.2"; version="1.9.2"; status="MAINTAINED"; uses:="org.apiguardian.api,org.junit.platform.commons.annotation"
              junit-platform-suite-api [79]
                No resolution report for the bundle.  Unresolved requirement: Import-Package: org.junit.platform.suite.api; version="[1.9.0,2.0.0)"
    -> Export-Package: org.junit.platform.suite.api; bundle-symbolic-name="junit-platform-suite-api"; bundle-version="1.9.2"; version="1.9.2"; status="MAINTAINED"; uses:="org.apiguardian.api,org.junit.platform.commons.annotation"
```

The question is - is this a user error, i.e. something missing in my target platform? Or should this work out of the box?

If it's something in the target platform can this issue be turned into a feature request to perform some validation ahead of the launch and report this to the user?

Target Platform State looks ok, though.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/191472/225046786-f9beb617-13d1-4857-8bba-ef8a9f7f94e6.png">

**Comment by vik-chand** [comment]
I am able to sample a sample Junit 5 plugin test here
Version: 2023-06 (4.28)
Build id: I20230313-0110
<img width="877" alt="image" src="https://user-images.githubusercontent.com/99390647/225211315-8b65d880-98ec-4bbe-84f3-f3fe1f023854.png">

**Comment by merks** [comment]
Yes, I figured such things are well tested.  We really need a way to reproduce the problem and then most likely it's something missing from the target platform.  I would expect the launcher to notice missing things.  The "Validate" button in the launcher's dialog detects no problem?
