### ISSUE TITLE
NPE after loading target platform using Eclipse 4.27

### ISSUE THREAD

**Issue by mfvalenta** [eclipse-pde/eclipse.pde#507]
After loading our target platform in Eclipse 4.27 RC2, the following NPE happens repeatedly and my java project will not build, making Eclipse 4.27 unusable. The cause appears to be https://github.com/eclipse-pde/eclipse.pde/pull/425.

!ENTRY org.eclipse.ui.ide 2 1 2023-03-15 14:32:42.071
!MESSAGE Problems occurred while trying to save the state of the workbench.
!SUBENTRY 1 org.eclipse.core.resources 2 566 2023-03-15 14:32:42.072
!MESSAGE Problems occurred during save.
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.lang.String.hashCode()" because "this.fBundleName" is null
	at org.eclipse.pde.internal.core.SourceLocationKey.hashCode(SourceLocationKey.java:56)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at org.eclipse.pde.internal.core.BundleManifestSourceLocationManager.setTargetBundles(BundleManifestSourceLocationManager.java:282)
	at org.eclipse.pde.internal.core.SourceLocationManager.initializeBundleManifestLocations(SourceLocationManager.java:469)
	at org.eclipse.pde.internal.core.SourceLocationManager.getBundleManifestLocator(SourceLocationManager.java:255)
	at org.eclipse.pde.internal.core.SourceLocationManager.getBundleManifestLocation(SourceLocationManager.java:247)
	at org.eclipse.pde.internal.core.SourceLocationManager.searchBundleManifestLocations(SourceLocationManager.java:340)
	at org.eclipse.pde.internal.core.SourceLocationManager.findSourcePath(SourceLocationManager.java:86)
	at org.eclipse.pde.internal.core.ClasspathUtilCore.getSourceAnnotation(ClasspathUtilCore.java:193)
	at org.eclipse.pde.internal.core.PDEClasspathContainer.addExternalPlugin(PDEClasspathContainer.java:90)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addPlugin(RequiredPluginsClasspathContainer.java:352)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:297)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:280)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.computePluginEntries(RequiredPluginsClasspathContainer.java:162)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.getClasspathEntries(RequiredPluginsClasspathContainer.java:112)
	at org.eclipse.jdt.internal.core.JavaModelManager$VariablesAndContainersSaveHelper.saveContainers(JavaModelManager.java:4534)
	at org.eclipse.jdt.internal.core.JavaModelManager$VariablesAndContainersSaveHelper.saveProjects(JavaModelManager.java:4601)
	at org.eclipse.jdt.internal.core.JavaModelManager$VariablesAndContainersSaveHelper.save(JavaModelManager.java:4442)
	at org.eclipse.jdt.internal.core.JavaModelManager.saveVariablesAndContainers(JavaModelManager.java:4421)
	at org.eclipse.jdt.internal.core.JavaModelManager.savingTimed(JavaModelManager.java:4654)
	at org.eclipse.jdt.internal.core.JavaModelManager.saving(JavaModelManager.java:4640)
	at org.eclipse.core.internal.resources.SaveManager.executeLifecycle(SaveManager.java:393)
	at org.eclipse.core.internal.resources.SaveManager$1.run(SaveManager.java:209)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.resources.SaveManager.broadcastLifecycle(SaveManager.java:212)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1170)
	at org.eclipse.core.internal.resources.Workspace.save(Workspace.java:2421)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.lambda$1(IDEWorkbenchAdvisor.java:554)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by mfvalenta** [comment]
The fix appears to be straightforward. Simply adding "&& sourceTarget.getSymbolicName() != null" to the check in the below method in org.eclipse.pde.internal.core.BundleManifestSourceLocationManager allows the build to happen.

	public void setTargetBundles(TargetBundle[] bundles) {
		fPluginToTargetBundle = new LinkedHashMap<>();
		for (TargetBundle bundle : bundles) {

			if (bundle.isSourceBundle()) {
				// collect it in the map ...
				BundleInfo sourceTarget = bundle.getSourceTarget();
				if (sourceTarget != null && sourceTarget.getSymbolicName() != null) {
					try {
						Version version = Version.parseVersion(sourceTarget.getVersion());
						fPluginToTargetBundle.put(new SourceLocationKey(sourceTarget.getSymbolicName(), version),
								bundle);
					} catch (IllegalArgumentException e) {
						// can't parse the version...
					}
				}
			}
		}
	}

**Comment by akurtakov** [comment]
What do you think about providing a PR with the fix and maybe even a junit test that verifies this doesn't regress again?

**Comment by laeubi** [comment]
What seem to happen here is that you have a source bundle that claims to be the source for a bundle that has no symbolic name, what seems invalid.

@mfvalenta any chance you can attach a (remote) debugger to your eclipse and see what kind of bundle is causing this?
If you know the culprit it might be a workaround to exclude that source bundle from your target until this is fixed.

**Comment by mfvalenta** [comment]
@akurtakov I'm not setup to provide PRs and I wouldn't know where to start in creating a JUnit. Out target is huge so it would be difficult to isolate the issue, I suspect.

@laeubi I've patched my Eclipse so the issue no longer occurs for me. However, it will prevent the rest of the IBM ELM team from adopting 4.27.

**Comment by laeubi** [comment]
@mfvalenta if you can path your eclipse you should be able to just submit your patch to Github, in the very basic manner hit the edit button in the web-page and paste your patched code there, then create a PR for this repository.

Beside that, you could also add a system.out line or something like that to better understand whats going on.

**Comment by vik-chand** [comment]
> What do you think about providing a PR with the fix and maybe even a junit test that verifies this doesn't regress again?

It will be a good if you provide PR ( even without junit)

**Comment by dstoch** [comment]
I have the same issue.

> @laeubi I've patched my Eclipse so the issue no longer occurs for me. However, it will prevent the rest of the our team from adopting 4.27.

@mfvalenta Could you tell more about your patch? Do you have any corrected version of some Eclipse bundle (org.eclipse.jface ?) you can share, until this will be fixed in official version?

**Comment by farmboy0** [comment]
Is there a way to get this fix into 4.27? its not in the official 4.27 update site.

**Comment by HannesWell** [comment]
> Is there a way to get this fix into 4.27? its not in the official 4.27 update site.

This fix was only applied to 4.28 and not 4.27 and as far as I can tell there is no patch planned for 4.27.
You can use the 4.28-I-builds repo to get the latest nightly builds from: https://download.eclipse.org/eclipse/updates/4.28-I-builds/
Or if you don't want to have the very latest bits you can consume the 2023-06 M1 SimRel release at
https://download.eclipse.org/releases/2023-06/
This repo will be updated with M2, M3, RC1, RC2 and eventually with the 2023-06 GA release in June.
If you just want M1 you can reference the (currently) only sub-repo, but that will likely vanish after the GA release and only the GA sub-repo will be retained (forever).
