### ISSUE TITLE
Strange error message when executing api tools checks

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#512]
I tried to execute the api tools check with the aggregator build but got:

```
[2023-03-17T06:03:28.652Z] 	[/opt/tools/java/openjdk/jdk-17/latest/bin/java, -Xmx2048M, -Dp2.RepositoryPreferences.retryOnSocketTimeout=true, -Dp2.RepositoryPreferences.connectionRetryCount=3, -Dp2.RepositoryPreferences.connectionMsRetryDelay=500, -Dorg.eclipse.ecf.provider.filetransfer.retrieve.readTimeout=10000, -jar, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.400.v20210924-0641/org.eclipse.equinox.launcher-1.6.400.v20210924-0641.jar, -install, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/apiAnalyzer-workspace, -configuration, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/apiAnalyzer-workspace/configuration, -data, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/apiAnalyzer-workspace/data, -application, org.eclipse.pde.api.tools.apiAnalyzer, -project, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/eclipse.platform.ui/bundles/org.eclipse.core.databinding.observable, -baseline, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/eclipse.platform.ui/bundles/org.eclipse.core.databinding.observable/target/org.eclipse.core.databinding.observable-apiBaseline.target, -dependencyList, /home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/eclipse.platform.ui/bundles/org.eclipse.core.databinding.observable/target/dependencies-list.txt, -failOnError]
[2023-03-17T06:03:36.900Z] java.lang.IllegalStateException: Profile not locked due to exception: The folder "/home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/apiAnalyzer-workspace/data/.metadata/.plugins/org.eclipse.pde.core/.p2/org.eclipse.equinox.p2.engine/profileRegistry/TARGET_DEFINITION%58;ile%58;%47;home%47;jenkins%47;agent%47;workspace%47;latform.releng.aggregator_PR-974%47;eclipse.platform.ui%47;bundles%47;org.eclipse.core.databinding.observable%47;target%47;org.eclipse.core.databinding.observable-apiBaseline.target-816379513.profile" is read-only.
[2023-03-17T06:03:36.900Z] 	at org.eclipse.equinox.internal.p2.engine.ProfileLock.lock(ProfileLock.java:113)
[2023-03-17T06:03:36.900Z] 	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.internalLockProfile(SimpleProfileRegistry.java:896)
[2023-03-17T06:03:36.900Z] 	at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.lockProfile(SimpleProfileRegistry.java:867)
[2023-03-17T06:03:36.900Z] 	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:72)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.pde.internal.core.target.P2TargetUtils.resolveWithPlanner(P2TargetUtils.java:1042)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:828)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:404)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.pde.api.tools.internal.ApiAnalysisApplication.setBaseline(ApiAnalysisApplication.java:278)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.pde.api.tools.internal.ApiAnalysisApplication.start(ApiAnalysisApplication.java:124)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.equinox.internal.app.AnyThreadAppLauncher.run(AnyThreadAppLauncher.java:30)
[2023-03-17T06:03:36.901Z] 	at java.base/java.lang.Thread.run(Thread.java:833)
[2023-03-17T06:03:36.901Z] Caused by: java.io.IOException: The folder "/home/jenkins/agent/workspace/latform.releng.aggregator_PR-974/apiAnalyzer-workspace/data/.metadata/.plugins/org.eclipse.pde.core/.p2/org.eclipse.equinox.p2.engine/profileRegistry/TARGET_DEFINITION%58;ile%58;%47;home%47;jenkins%47;agent%47;workspace%47;latform.releng.aggregator_PR-974%47;eclipse.platform.ui%47;bundles%47;org.eclipse.core.databinding.observable%47;target%47;org.eclipse.core.databinding.observable-apiBaseline.target-816379513.profile" is read-only.
[2023-03-17T06:03:36.901Z] 	at org.eclipse.osgi.internal.location.BasicLocation.lock(BasicLocation.java:220)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.osgi.internal.location.BasicLocation.lock(BasicLocation.java:193)
[2023-03-17T06:03:36.901Z] 	at org.eclipse.equinox.internal.p2.engine.ProfileLock.lock(ProfileLock.java:108)
```

Full job log can be found here: https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-974/1/

**Comment by vik-chand** [comment]
Dup of https://bugs.eclipse.org/bugs/show_bug.cgi?id=568474
"The message says it's read only, but it I reduce the path to the plugin, it works"
@tjwatson  Does the ProfileLock cause exception during if the path length is big ( > 256 characters)

**Comment by merks** [comment]
@vik-chand  See the discussion here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/974#issuecomment-1473342595

It looks like the problem is purely one of file names being too long and that PDE's encoding scheme contributes to making names longer than the expected cut-off size.  For both Windows and Linux we've tested that the name is too long to be able to create a file with that name...

Most likely we are better to significantly reduce the filename size...

**Comment by laeubi** [comment]
@merks I know its maybe a hack, but what do you think about having a system property that controls how profile ids are generated? Then it would be possible to try that out with an ibuild for example?

**Comment by merks** [comment]
I will create a PR and I will test in a runtime launch what the behavior is for before and after changes, i.e.,  how badly do things go wrong when the profile isn't found.  We can discuss further on the PR when I get to that in the next day or two...
