### ISSUE TITLE
Several test failures under windows because not correctly closed files

### ISSUE THREAD

**Issue by laeubi** [eclipse-pde/eclipse.pde#523]
```
2023-03-21T12:13:29.7080967Z Contains: Could not delete: D:\a\eclipse.pde\eclipse.pde\ui\org.eclipse.pde.ui.tests\target\work\data\test.headerformatting\META-INF\MANIFEST.MF.
2023-03-21T12:13:29.7081688Z java.nio.file.FileSystemException: D:\a\eclipse.pde\eclipse.pde\ui\org.eclipse.pde.ui.tests\target\work\data\test.headerformatting\META-INF\MANIFEST.MF: The process cannot access the file because it is being used by another process
2023-03-21T12:13:29.7082382Z 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
2023-03-21T12:13:29.7082786Z 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
2023-03-21T12:13:29.7083176Z 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
2023-03-21T12:13:29.7083584Z 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
2023-03-21T12:13:29.7083999Z 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
2023-03-21T12:13:29.7084365Z 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
2023-03-21T12:13:29.7084719Z 	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:222)
2023-03-21T12:13:29.7085144Z 	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:250)
2023-03-21T12:13:29.7085535Z 	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:139)
2023-03-21T12:13:29.7085912Z 	at org.eclipse.core.internal.localstore.DeleteVisitor.delete(DeleteVisitor.java:66)
2023-03-21T12:13:29.7086292Z 	at org.eclipse.core.internal.localstore.DeleteVisitor.visit(DeleteVisitor.java:156)
2023-03-21T12:13:29.7086653Z 	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:119)
2023-03-21T12:13:29.7087079Z 	at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:364)
2023-03-21T12:13:29.7087852Z 	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:364)
2023-03-21T12:13:29.7194711Z 	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:399)
2023-03-21T12:13:29.7196145Z 	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:856)
2023-03-21T12:13:29.7197126Z 	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1806)
2023-03-21T12:13:29.7256058Z 	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:771)
2023-03-21T12:13:29.7256604Z 	at org.eclipse.core.internal.resources.Project.delete(Project.java:326)
2023-03-21T12:13:29.7257119Z 	at org.eclipse.pde.ui.tests.util.ProjectUtils.deleteWorkspaceProjects(ProjectUtils.java:252)
2023-03-21T12:13:29.7257630Z 	at org.eclipse.pde.ui.tests.util.ProjectUtils.lambda$0(ProjectUtils.java:221)
2023-03-21T12:13:29.7258124Z 	at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:268)
2023-03-21T12:13:29.7263324Z 	at org.eclipse.pde.ui.tests.runtime.TestUtils$1.evaluate(TestUtils.java:271)
2023-03-21T12:13:29.7263785Z 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2023-03-21T12:13:29.7264174Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-03-21T12:13:29.7264574Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-03-21T12:13:29.7264943Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2023-03-21T12:13:29.7265291Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2023-03-21T12:13:29.7265651Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-03-21T12:13:29.7266032Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-03-21T12:13:29.7266436Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-03-21T12:13:29.7266835Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-03-21T12:13:29.7267236Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-03-21T12:13:29.7267621Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-03-21T12:13:29.7268009Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-03-21T12:13:29.7268400Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2023-03-21T12:13:29.7268994Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2023-03-21T12:13:29.7269608Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-03-21T12:13:29.7269978Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-03-21T12:13:29.7270360Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-03-21T12:13:29.7270757Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-03-21T12:13:29.7271132Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-03-21T12:13:29.7271489Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-03-21T12:13:29.7271919Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-03-21T12:13:29.7272269Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2023-03-21T12:13:29.7272619Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2023-03-21T12:13:29.7273027Z 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
2023-03-21T12:13:29.7273532Z 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
2023-03-21T12:13:29.7274011Z 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
2023-03-21T12:13:29.7274527Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
2023-03-21T12:13:29.7275095Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
2023-03-21T12:13:29.7275665Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
2023-03-21T12:13:29.7276241Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
2023-03-21T12:13:29.7276967Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
2023-03-21T12:13:29.7277593Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
2023-03-21T12:13:29.7279393Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2023-03-21T12:13:29.7280055Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2023-03-21T12:13:29.7280589Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2023-03-21T12:13:29.7281112Z 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
2023-03-21T12:13:29.7281785Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
2023-03-21T12:13:29.7282392Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
2023-03-21T12:13:29.7282989Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
2023-03-21T12:13:29.7283507Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-21T12:13:29.7284279Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-03-21T12:13:29.7284872Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-21T12:13:29.7285330Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-03-21T12:13:29.7285804Z 	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
2023-03-21T12:13:29.7286570Z 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
2023-03-21T12:13:29.7287079Z 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
2023-03-21T12:13:29.7287604Z 	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:142)
2023-03-21T12:13:29.7288747Z 	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:42)
2023-03-21T12:13:29.7289673Z 	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$1(E4Testable.java:127)
2023-03-21T12:13:29.7290128Z 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
2023-03-21T12:13:29.7290564Z 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
2023-03-21T12:13:29.7291023Z 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
2023-03-21T12:13:29.7291815Z 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
2023-03-21T12:13:29.7292294Z 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
2023-03-21T12:13:29.7292777Z 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
2023-03-21T12:13:29.7293278Z 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
2023-03-21T12:13:29.7293786Z 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
2023-03-21T12:13:29.7294212Z 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
2023-03-21T12:13:29.7294630Z 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
2023-03-21T12:13:29.7295082Z 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
2023-03-21T12:13:29.7295512Z 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
2023-03-21T12:13:29.7295967Z 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
2023-03-21T12:13:29.7296493Z 	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:34)
2023-03-21T12:13:29.7297072Z 	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:129)
2023-03-21T12:13:29.7297916Z 	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:44)
2023-03-21T12:13:29.7298428Z 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
2023-03-21T12:13:29.7298962Z 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
2023-03-21T12:13:29.7299715Z 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
2023-03-21T12:13:29.7300199Z 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
2023-03-21T12:13:29.7300636Z 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
2023-03-21T12:13:29.7301078Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-21T12:13:29.7301563Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-03-21T12:13:29.7309754Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-21T12:13:29.7310353Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-03-21T12:13:29.7310941Z 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
2023-03-21T12:13:29.7311353Z 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
2023-03-21T12:13:29.7311714Z 	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
2023-03-21T12:13:29.7312073Z 	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by iloveeclipse** [comment]
@laeubi : 
1) where is this stack trace is coming from, and
2) are there more opened files reported?

**Comment by laeubi** [comment]
https://pipelines.actions.githubusercontent.com/serviceHosts/3431c4c7-1fdc-4d95-b2cd-ce121ae32eaa/_apis/pipelines/1/runs/1777/signedlogcontent/10?urlExpires=2023-03-21T17%3A21%3A16.3974881Z&urlSigningMethod=HMACV1&urlSignature=dXVs4utFnnZJR2VR3ZzSU%2FFDOHSi9%2FZfrRWtbOVaD6A%3D

Then you can search for `java.nio.file.FileSystemException` ... hopefully most of them use one function that fix several tests.

**Comment by iloveeclipse** [comment]
> Then you can search for

`{"count":11,"value":"Uri expired"}`



> hopefully most of them use one function that fix several tests.

Nope. The one function I saw was used from one test only.

**Comment by iloveeclipse** [comment]
@laeubi : if you could point to some more output we continue fixing opened files, or we can close this after merge of #524 .

**Comment by laeubi** [comment]
Here is the output of current failing tests:
https://github.com/eclipse-pde/eclipse.pde/runs/12170122389

Full Buildlog is here:
https://pipelines.actions.githubusercontent.com/serviceHosts/3431c4c7-1fdc-4d95-b2cd-ce121ae32eaa/_apis/pipelines/1/runs/1784/signedlogcontent/8?urlExpires=2023-03-21T18%3A17%3A35.6641301Z&urlSigningMethod=HMACV1&urlSignature=LLoPrHb7R3xxCu9KCo9aFfY3Nxnc%2FzdBKw9JWOnUf3k%3D

**Comment by iloveeclipse** [comment]
I don't see FileSystemException in the logs above. If you see some, just paste stack trace here.

**Comment by laeubi** [comment]
I think you have successfully fixed those then!

**Comment by jarthana** [comment]
@laeubi Can you confirm that the fix works for you and mark them accordingly? TIA!
