### ISSUE TITLE
 java.lang.NoClassDefFoundError: in recent I-Build required "Clean all projects" to disappear

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#602]
In Build id: I20230522-1800 I have the issue that I get "random"  java.lang.NoClassDefFoundError exceptions.

To reproduce:

- Clone and import example projects from https://github.com/vogellacompany/eclipse4book
- Activate target platform file pointing to latest I-build using the target-platform.target file
- Start via the com.vogella.tasks.product file

-> Work fine 

Edit one Java file, e.g. OpenEditorHandler-> save

- Start via the com.vogella.tasks.product file

--> Fails

Do a clean and start again via the product file -> Works again

WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
!SESSION 2023-05-25 13:45:36.893 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product com.vogella.tasks.ui.product -clearPersistedState
Command-line arguments:  -product com.vogella.tasks.ui.product -data C:\Users\vogella\workspace\eclipse4book/../runtime-com.vogella.tasks.product -dev file:C:/Users/vogella/workspace/eclipse4book/.metadata/.plugins/org.eclipse.pde.core/com.vogella.tasks.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -clearPersistedState

!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-05-25 13:45:38.545
!MESSAGE Unable to create class 'com.vogella.tasks.ui.handlers.RemoveTaskHandler' from bundle '14'
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: TaskService
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:406)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:322)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.internal.workbench.addons.HandlerProcessingAddon.processActiveHandler(HandlerProcessingAddon.java:141)
	at org.eclipse.e4.ui.internal.workbench.addons.HandlerProcessingAddon.postConstruct(HandlerProcessingAddon.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:987)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:141)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:395)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:336)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:227)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:94)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:37)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:276)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.NoClassDefFoundError: TaskService
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at org.eclipse.e4.core.internal.di.InjectorImpl.getDeclaredMethods(InjectorImpl.java:824)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processMethods(InjectorImpl.java:714)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processClass(InjectorImpl.java:660)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processClassHierarchy(InjectorImpl.java:640)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:117)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:395)
	... 35 more
Caused by: java.lang.ClassNotFoundException: TaskService cannot be found by com.vogella.tasks.ui_1.0.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 44 more

**Comment by HannesWell** [comment]
Might be too simple, but do you have auto-build enabled?

In generell there was no change in PDE since the M3 freeze.

**Comment by vogella** [comment]
Yes, auto-build is on, but even if not it would not explain why I get Class not found exceptions after a change in the source file.

**Comment by laeubi** [comment]
@vogella something is messed up here, as you should (just in case) get an error that `com.vogella.tasks.model.TaskService` is not found but the error indicates that `TaskService` (in the default package) is not found, so I suspect something in the E4 model is not working as expected.

I sometimes noticed that refactoring / rename of an item complete mess up the E4 xml, maybe something similar happens here?

**Comment by vogella** [comment]
@laeubi adding a whitespace character to a source file is sufficient to trigger this errror. A clean workspace removes this error again.

**Comment by vogella** [comment]
Doing some more testing this morning (because customer work starts which prevents me from looking into this / testing):

* Also happens for the same workspace if I use Eclipse 4.27 -> Good news, no new regression
* Also happens for the same workspace if I use Eclipse 4.26-> Good news, no new regression
* Does NOT happen in a fresh SDK download if I import the projects from Git -> That is great, as we have a workaround

Looks like something is wrong with the used workspace, I guess that makes is unreasonable (effortwise) to find the real cause, I will switch to my  workspace and close this issue.

**Comment by laeubi** [comment]
You might want to take a look at the classfile, I suspect this is not an PDE issue (the error comes OSGi and is most certainly correct as there is no `TaskService` in the default package).

**Comment by vogella** [comment]
> You might want to take a look at the classfile, I suspect this is not an PDE issue (the error comes OSGi and is most certainly correct as there is no `TaskService` in the default package).

It is not only this class, it is any class, for example CustomTabFolderRenderer is after a whitespace change not able to find SWT CTabFolder
