### ISSUE TITLE
org.eclipse.pde.build.internal.tests.p2.PublishingTests fails

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#661]
As of today 14 tests fail in I-Builds across platforms:
for example:

https://download.eclipse.org/eclipse/downloads/drops4/I20230710-1800/testresults/html/org.eclipse.pde.build.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```
Caused by: /Users/genie.releng/workspace/AutomatedTests/ep429I-unit-mac64-java17/workarea/I20230710-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/pdebuild_folder/pde.build/PublishBundle_p2infCUs/assemble.org.eclipse.pde.build.container.feature.p2.xml:72: Replace: source file /Users/genie.releng/workspace/AutomatedTests/ep429I-unit-mac64-java17/workarea/I20230710-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/pdebuild_folder/pde.build/PublishBundle_p2infCUs/features/org.eclipse.pde.build.container.feature/product/p2.inf doesn't exist
at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:645)
at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:533)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
at jdk.internal.reflect.GeneratedMethodAccessor1211.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
at org.eclipse.ant.internal.core.ant.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:32)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
... 198 more
```

**Comment by iloveeclipse** [comment]
I assume this is side effect of https://github.com/eclipse-platform/eclipse.platform/pull/516.
Ant support libraries are built using smallest possible JLS target, and this PR above requires at least Java 8 JLS.
See also https://github.com/eclipse-platform/eclipse.platform/issues/570.

**Comment by jukzi** [comment]
There is (also?) some regression from https://github.com/eclipse-pde/eclipse.pde/pull/637

**Comment by jukzi** [comment]
Is there any reason that such tests no executed in CI  / Integration Builds?
can't see "org.eclipse.pde.build" or "PublishingTests" in
https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-662/1/testReport/

**Comment by iloveeclipse** [comment]
> Is there any reason that such tests no executed in CI / Integration Builds? can't see "org.eclipse.pde.build" or "PublishingTests" in https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-662/1/testReport/

The reason is that they fail on jenkins (at least some of pde tests, if I remember it right). Ideally one would fix that but as usually it is not high prio for anyone.

**Comment by HannesWell** [comment]
> Is there any reason that such tests no executed in CI / Integration Builds? can't see "org.eclipse.pde.build" or "PublishingTests" in https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-662/1/testReport/

If anybody wants to make them run in the CI, this would be of course more then welcome.
One just has to remove their disabling in:
https://github.com/eclipse-pde/eclipse.pde/blob/13c0d89507ed4adfbf0bfff1f5e8c5d25db47203/build/org.eclipse.pde.build.tests/build.properties#L23

In case just running all tests does not work, you maybe want to start only with the test suite `org.eclipse.pde.build.tests.PDEBuildTestSuite`. To enable it, just set in the build.properties:
`pom.model.property..testClass = org.eclipse.pde.build.tests.PDEBuildTestSuite`
