### ISSUE TITLE
Component in the baseline 'Modular API Baseline' is disposed

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#663]
While working with OOmphed IDE i see exceptions like this in log:
```
org.eclipse.core.runtime.CoreException: Component '%systemBundle' in the baseline 'Modular API Baseline' is disposed
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.baselineDisposed(BundleComponent.java:1259)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.getBundleDescription(BundleComponent.java:980)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.createApiDescription(BundleComponent.java:388)
	at org.eclipse.pde.api.tools.internal.model.Component.getApiDescription(Component.java:106)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.hasApiDescription(BundleComponent.java:1133)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.getDeltaForMethod(ClassFileComparator.java:1701)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.getDelta(ClassFileComparator.java:1232)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.checkTypeMembers(ClassFileComparator.java:655)
	at org.eclipse.pde.api.tools.internal.comparator.ClassFileComparator.getDelta(ClassFileComparator.java:1267)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator$2.visit(ApiComparator.java:771)
	at org.eclipse.pde.api.tools.internal.model.ArchiveApiTypeContainer.accept(ArchiveApiTypeContainer.java:191)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.internalCompare(ApiComparator.java:655)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.compare(ApiComparator.java:289)
	at org.eclipse.pde.api.tools.internal.provisional.comparator.ApiComparator.compare(ApiComparator.java:315)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.checkCompatibility(BaseApiAnalyzer.java:1509)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.analyzeComponent(BaseApiAnalyzer.java:268)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.buildAll(ApiAnalysisBuilder.java:933)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.work(ApiAnalysisBuilder.java:416)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.build(ApiAnalysisBuilder.java:396)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1023)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
![image](https://github.com/eclipse-pde/eclipse.pde/assets/51790620/c0740313-72b1-44f9-b3b9-8b983f6c98e0)

don't remember what exactly i did back then but probably it happened during starting ide or shortly after.
Happened twice:
![image](https://github.com/eclipse-pde/eclipse.pde/assets/51790620/624a5ce8-31ad-4636-bfaf-4c5e14c5be9d)

**Comment by HannesWell** [comment]
`%systemBundle` is the literal name of the `o.e.osgi` bundle. As Side-Note: the component should substitute the bundle Name.

Maybe it is related to the repetitive API-Tools Test failure in the Windows build?

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-pde/eclipse.pde/issues/145
