### ISSUE TITLE
Random failing UpdateUnitVersionsCommandTests

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#666]
https://download.eclipse.org/eclipse/downloads/drops4/R-4.28-202306050440/testresults/html/org.eclipse.pde.genericeditor.extension.tests_ep428I-unit-win32-java17_win32.win32.x86_64_17.html
```

ID: org.eclipse.fake.7 has the incorrect version. expected:<[1.0.0.v2]> but was:<[0.0.0]>

org.junit.ComparisonFailure: ID: org.eclipse.fake.7 has the incorrect version. expected:<[1.0.0.v2]> but was:<[0.0.0]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.confirmVersionUpdates(UpdateUnitVersionsCommandTests.java:92)
at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.testVersionSort(UpdateUnitVersionsCommandTests.java:55)
```

**Comment by jukzi** [comment]
same in 
https://download.eclipse.org/eclipse/downloads/drops4/I20241118-0600/testresults/html/org.eclipse.pde.genericeditor.extension.tests_ep434I-unit-macosx-aarch64-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
Enhanced info from https://download.eclipse.org/eclipse/downloads/drops4/I20241120-0600/testresults/html/org.eclipse.pde.genericeditor.extension.tests_ep434I-unit-macosx-aarch64-java17_macosx.cocoa.aarch64_17.html

```
org.junit.ComparisonFailure: ID: org.eclipse.fake.6 has the incorrect version. updatedText=<target>
<locations>
<location>
<unit id="org.eclipse.fake.1" version="0.0.0"/>
<unit id="org.eclipse.fake.2" version="0.0.0"/>
<unit id="org.eclipse.fake.3" version="0.0.0"/>
<unit id="org.eclipse.fake.4" version="0.0.0"/>
<unit id="org.eclipse.fake.5" version="0.0.0"/>
<unit id="org.eclipse.fake.6" version="0.0.0"/>
<unit id="org.eclipse.fake.7" version="0.0.0"/>
<repository location="bundleentry://349.fwk733886212/testing-files/testing-sites/MultipleUnitsConfirmSorting/"/>
</location>

```

**Comment by jukzi** [comment]
the string is calculated in [UpdateUnitVersions.java](https://github.com/eclipse-pde/eclipse.pde/blob/5ab1e215fa09674c37a00e49a9d846a5758ab8df/ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/command/UpdateUnitVersions.java#L110):

**Comment by jukzi** [comment]
A version of 0 could means `org.eclipse.pde.internal.genericeditor.target.extension.model.RepositoryCache.fetchP2UnitsFromRepos(List<String>)` 
may have not returned any version. Potential Exceptions are ignored in 
`org.eclipse.pde.internal.genericeditor.target.extension.model.RepositoryCache.getFutureValue()` and not even logged.

**Comment by jukzi** [comment]
The result version are stored in `org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository.units`, which is only partially accessed with "synchronized"

**Comment by trancexpress** [comment]
If I set a breakpoint at the start of `org.eclipse.pde.internal.genericeditor.target.extension.command.UpdateUnitVersions.getDocument()` and debug the test, resume the breakpoint, I see:

```
!ENTRY org.eclipse.pde.genericeditor.extension 2 0 2025-11-14 12:34:50.660
!MESSAGE Cannot invoke "org.eclipse.equinox.internal.p2.repository.Transport.download(java.net.URI, java.io.OutputStream, org.eclipse.core.runtime.IProgressMonitor)" because the return value of "org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.getTransport()" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.equinox.internal.p2.repository.Transport.download(java.net.URI, java.io.OutputStream, org.eclipse.core.runtime.IProgressMonitor)" because the return value of "org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.getTransport()" is null
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.handleRemoteIndexFile(AbstractRepositoryManager.java:797)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadIndexFile(AbstractRepositoryManager.java:791)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:727)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.p2.repository.metadata.IMetadataRepositoryManager.loadRepository(IMetadataRepositoryManager.java:101)
	at org.eclipse.pde.internal.genericeditor.target.extension.p2.P2Fetcher.fetchAvailableUnits(P2Fetcher.java:63)
	at org.eclipse.pde.internal.genericeditor.target.extension.model.RepositoryCache.lambda$11(RepositoryCache.java:106)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Then the test shows a dialog:

<img width="534" height="180" alt="Image" src="https://github.com/user-attachments/assets/63f6b734-3591-40eb-b7de-b124e4065113" />

And fails:

```
org.junit.ComparisonFailure: ID: org.eclipse.fake.7 has the incorrect version. updatedText=<target>
<locations>
<location>
<unit id="org.eclipse.fake.1" version="0.0.0"/>
<unit id="org.eclipse.fake.2" version="0.0.0"/>
<unit id="org.eclipse.fake.3" version="0.0.0"/>
<unit id="org.eclipse.fake.4" version="0.0.0"/>
<unit id="org.eclipse.fake.5" version="0.0.0"/>
<unit id="org.eclipse.fake.6" version="0.0.0"/>
<unit id="org.eclipse.fake.7" version="0.0.0"/>
<repository location="bundleentry://169.fwk218491387/testing-files/testing-sites/MultipleUnitsConfirmSorting/"/>
</location>
</locations>
</target> expected:<[1.0.0.v2]> but was:<[0.0.0]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.confirmVersionUpdates(UpdateUnitVersionsCommandTests.java:93)
	at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.testVersionSort(UpdateUnitVersionsCommandTests.java:55)
```

**Comment by trancexpress** [comment]
The cause for the error from the description is probably: https://github.com/eclipse-pde/eclipse.pde/issues/2135

```
ID: org.eclipse.fake.7 has the incorrect version. expected:<[1.0.0.v2]> but was:<[0.0.0]>

org.junit.ComparisonFailure: ID: org.eclipse.fake.7 has the incorrect version. expected:<[1.0.0.v2]> but was:<[0.0.0]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.confirmVersionUpdates(UpdateUnitVersionsCommandTests.java:92)
at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.testVersionSort(UpdateUnitVersionsCommandTests.java:55)
```

I'm not sure if this one can also occur due to the same problem, the cause might be different:

```
Running org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.622 s <<< FAILURE! -- in org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests
org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.testUpdateRequired -- Time elapsed: 0.466 s
org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.testVersionSort -- Time elapsed: 0.155 s <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.confirmVersionUpdates(UpdateUnitVersionsCommandTests.java:84)
	at org.eclipse.pde.genericeditor.extension.tests.UpdateUnitVersionsCommandTests.testVersionSort(UpdateUnitVersionsCommandTests.java:55)
```
