### ISSUE TITLE
[mac] DependentUsageTests failed hard on I-Build

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#669]
40 fails on macosx.cocoa.x86_64_17 today:
https://download.eclipse.org/eclipse/downloads/drops4/I20230716-1800/testresults/html/org.eclipse.pde.api.tools.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

like for example

```
junit.framework.ComparisonFailure: Unexpected problem(s)!!!.
----------- Expected ------------

------------ but was ------------
Problem : There is a possible API baseline mismatch since none of the workspace projects is in the baseline. [ resource : </> range : <-1,-1> category : <-1> severity : <0>]

--------- Difference is ----------
expected:<[]> but was:<[Problem : There is a possible API baseline mismatch since none of the workspace projects is in the baseline. [ resource : </> range : <-1,-1> category : <-1> severity : <0>]
]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:275)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assumeEquals(TestCase.java:295)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.expectingNoProblemsFor(ApiBuilderTest.java:236)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.expectingNoProblemsFor(ApiBuilderTest.java:180)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.expectingNoProblems(ApiBuilderTest.java:172)
at org.eclipse.pde.api.tools.builder.tests.usage.DependentUsageTests.deployTest(DependentUsageTests.java:102)
at org.eclipse.pde.api.tools.builder.tests.usage.DependentUsageTests.test10(DependentUsageTests.java:411)
at org.eclipse.pde.api.tools.builder.tests.usage.DependentUsageTests.testAddExtendImplementRestriction(DependentUsageTests.java:389)

```

**Comment by HannesWell** [comment]
The test passes in the latest I-builds, so I think we can consider this fixed.

**Comment by iloveeclipse** [comment]
Still there: https://download.eclipse.org/eclipse/downloads/drops4/I20250521-1800/testresults/html/org.eclipse.pde.api.tools.tests_ep436I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

Note, it happens randomly.

**Comment by trancexpress** [comment]
Seen also in the last build:

https://download.eclipse.org/eclipse/downloads/drops4/I20260225-1800/reports.html#tests

https://download.eclipse.org/eclipse/downloads/drops4/I20260225-1800/testresults/html/org.eclipse.pde.api.tools.tests_ep439I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

```
	Unexpected problem(s)!!!. ----------- Expected ------------ ------------ but was ------------ Problem : There is a possible API baseline mismatch since none of the workspace projects is in the baseline. [ resource : </> range : <-1,-1> category : <-1> severity : <0>] ---------------------- ---------- expected:<[]> but was:<[Problem : There is a possible API baseline mismatch since none of the workspace projects is in the baseline. [ resource : </> range : <-1,-1> category : <-1> severity : <0>] ]>

junit.framework.ComparisonFailure: Unexpected problem(s)!!!.
----------- Expected ------------

------------ but was ------------
Problem : There is a possible API baseline mismatch since none of the workspace projects is in the baseline. [ resource : </> range : <-1,-1> category : <-1> severity : <0>]

---------------------- ----------
expected:<[]> but was:<[Problem : There is a possible API baseline mismatch since none of the workspace projects is in the baseline. [ resource : </> range : <-1,-1> category : <-1> severity : <0>]
]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:265)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assumeEquals(TestCase.java:285)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.expectingNoProblemsFor(ApiBuilderTest.java:233)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.expectingNoProblemsFor(ApiBuilderTest.java:182)
at org.eclipse.pde.api.tools.builder.tests.ApiBuilderTest.expectingNoProblems(ApiBuilderTest.java:174)
at org.eclipse.pde.api.tools.builder.tests.usage.DependentUsageTests.deployTest(DependentUsageTests.java:101)
at org.eclipse.pde.api.tools.builder.tests.usage.DependentUsageTests.test10(DependentUsageTests.java:410)
at org.eclipse.pde.api.tools.builder.tests.usage.DependentUsageTests.testAddExtendImplementRestriction(DependentUsageTests.java:388)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.runTest(TestCase.java:970)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```
