### ISSUE TITLE
Run as Plug-in test still adds the fragments to the runtime which are invalid for the platform

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#68]
I'm currently helping a bit with WindowBuilder trying to cleanup the repo and to activate more tests.

If I open org.eclipse.wb.tests.utils.CommonTests and run it as plug-ins tests I see the following errors:

org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wb.os.linux [278]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=gtk) (osgi.os=linux))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

!ENTRY org.eclipse.wb.os.macosx 4 0 2022-05-03 15:13:27.816
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wb.os.macosx [279]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=macosx)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)

Is that expected? I thought @HannesWell implemented filtering for fragments which are do not fit to the selected  platform.

**Comment by merks** [comment]
For Oomph we include all platform specific fragments in the target platform so when launching with all plugin, we generally see all kinds of such exceptions.   I find it annoying and would be really happy if PDE were smart enough not to include fragments that are filtered out by the current platform because clearly these are not appropriate to include...

**Comment by HannesWell** [comment]
I think this can be simply solved by excluding not resolved plug-ins when launching all plugins.
But at the moment I'm struggling to verify the fix locally.

If I use `Eclipse-PlatformFilter: (& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86_64))` in a fragment on my windows computer it resolves successfully and if I change one argument e.g. to linux/gtk the resolution in the workspace fails due the the wrong environment. If I launch the not matching variant with all plug-ins and ignore all warnings the resolution errors you mentioned are not shown in the Console.

Since the `Eclipse-PlatformFilter` is used in the plug-in you mentioned I assume that Equinox translates them into the generic capabilities you mentioned as well. If I use `Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32))"` on my windows computer the Target Platform State view indicates that the fragment cannot be resolved due to missing requirements. Furthermore I'm not sure if the syntax is correct.

**Comment by HannesWell** [comment]
Created PR https://github.com/eclipse-pde/eclipse.pde/pull/181.
