### ISSUE TITLE
'Bundle "org.eclipse.jdt.junit5.runtime" not found' when running JUnit Plugin Tests in Eclipse 2023-03 on Windows

### ISSUE THREAD

**Issue by tivervac** [eclipse-pde/eclipse.pde#682]
We're in the progress of updating our product (both development and RCP target) to 2023-03 from 2022-03 (yes we're very late to the party). In the past, tests always ran fine on the command line via Tycho, and could be started and finished cleanly from within Eclipse (Run As > JUnit (Plug in) Test). After having upgraded, we ran into the issue where we couldn't get a project setup where both Tycho and JUnit Plugin tests in Eclipse were green.

The migration is now basically done and both Tycho and Eclipse Plugin Tests are green. We've achieved this by moving from Require-Bundle for `org.junit.jupiter` and `org.junit.platform` to import-package and getting rid of our `pomDependencies=consider`. We've not added the JUnit 5 containers to any of our projects as those caused more harm than good.

Sadly, having gotten so far, we only just noticed that Eclipse JUnit plugin tests fail on Windows, while being green on Linux and mac. Regular Eclipse JUnit tests as well as Tycho tests work fine on all platforms.

I'm trying to run a JUnit plugin test for one of our most basic plugins and get the following error (this is the same error we got on Linux before using `import-package`). The error is preceded by 100% CPU usage for about a minute, our guess is that this is OSGi trying to do dependency resolution.

```
!ENTRY org.eclipse.ui 4 0 2023-07-27 11:59:02.081
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Bundle "org.eclipse.jdt.junit5.runtime" not found. Possible causes include missing dependencies, too restrictive version ranges, or a non-matching required execution environment.
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.getClassLoader(RemotePluginTestRunner.java:123)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.readPluginArgs(RemotePluginTestRunner.java:173)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.init(RemotePluginTestRunner.java:130)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:67)
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$1(E4Testable.java:127)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:53)
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:47)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

Our manifest looks like this
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: com.sigasi.hdt.epl.ui.test
Bundle-SymbolicName: com.sigasi.hdt.epl.ui.test
Bundle-Version: 5.3.0.qualifier
Bundle-Vendor: Sigasi
Bundle-RequiredExecutionEnvironment: JavaSE-17
Require-Bundle: com.google.guava;bundle-version="[30.1.0,31.0.0)",
 com.sigasi.hdt.epl.ui;bundle-version="[5.3.0,5.3.1)",
 com.sigasi.hdt.epl;bundle-version="[5.3.0,5.3.1)",
 com.sigasi.hdt.epl.test;bundle-version="[5.3.0,5.3.1)",
 org.eclipse.xtext.testing;bundle-version="[2.29.0,2.30.0)",
 org.eclipse.xtext.ui.shared;bundle-version="[2.29.0,2.30.0)",
 org.eclipse.xtext.ui.testing;bundle-version="[2.29.0,2.30.0)",
 org.eclipse.lsp4j;bundle-version="[0.19.0,0.20.0)"
Bundle-ActivationPolicy: lazy
Automatic-Module-Name: com.sigasi.hdt.epl.ui.test
Import-Package: org.apache.log4j,
 org.junit.jupiter.api;version="[5.9.2,6)",
 org.junit.jupiter.api.function;version="[5.9.2,6)",
 org.junit.jupiter.api.condition;version="[5.9.2,6)",
 org.junit.platform.commons;version="[1.9.2,2)",
 org.junit.platform.engine;version="[1.9.2,2)"
```

And the classpath as follows
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins">
	</classpathentry>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

**Comment by tivervac** [comment]
This seems very much related to #505. Sadly that ticket was just closed without any comment explaining the solution.

Our TP includes the mentioned missing bundle

![image](https://github.com/eclipse-pde/eclipse.pde/assets/3389524/3fb6ac11-0714-49f8-aa4b-f80013ccfc37)

**Comment by laeubi** [comment]
I think as always the best is to demonstrate this with a runnable example, in this case a plugin + a target platform one should set for the test.

**Comment by tivervac** [comment]
While trying to get to a minimal example, I've discovered that Linux (and likely Mac) is also broken as long as you have a completely clean install (new p2 bundle pool, new ws, fresh git clone). Surprisingly only trying to change one of these (p2, ws, git clone) doesn't result in failure. At least that now makes it consistent over platforms.

Thus my current experimentation looks like this:
* My many months old Eclipse installation with a seasoned p2 and ws: green test
* A fresh p2 pool with a clean new ws: red test
* Same fresh p2 pool with seasoned WS: green test
* Seasoned Eclipse with seasoned p2 but the new WS: red test

Seems like I've narrowed it down to the WS, to be continued...

**Comment by tivervac** [comment]
I seem to have resolved it. There's probably still a bug at play here, but I won't be able to minimize this.

I was working on a part 1 merge request which included a new intermediary TP. A second, part 2, branch branched off from part 1 and introduced a new TP. Somehow if you fist go to part 1, then checkout to part 2, and do all the cache clearing, reloading, refreshing, restarting, rebuilding you want, the test remains red. If you instead oomph straight to part 2, the test is green.

I'm thinking that somehow the part 1 TP is faulty and part of it remains after moving to part 2.
