### ISSUE TITLE
BaseApiAnalyzer: Component 'Compare Support' in the baseline 'workspace' is disposed

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#732]
In platform workspace i switched JavaSE-17 Execution Environment to jdk 20. After that a lengthy build started and man this error was logged many times:
![image](https://github.com/eclipse-pde/eclipse.pde/assets/51790620/a7735c21-28e3-4386-b242-86ba140e8614)

```
org.eclipse.core.runtime.CoreException: Component 'Compare Support' in the baseline 'workspace' is disposed
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.baselineDisposed(BundleComponent.java:1238)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.getBundleDescription(BundleComponent.java:976)
	at org.eclipse.pde.api.tools.internal.model.BundleComponent.createApiDescription(BundleComponent.java:384)
	at org.eclipse.pde.api.tools.internal.model.Component.getApiDescription(Component.java:106)
	at org.eclipse.pde.api.tools.internal.builder.MethodLeakDetector.matchesSourceApiRestrictions(MethodLeakDetector.java:164)
	at org.eclipse.pde.api.tools.internal.builder.MethodLeakDetector.considerReference(MethodLeakDetector.java:145)
	at org.eclipse.pde.api.tools.internal.builder.ReferenceAnalyzer$Visitor.visit(ReferenceAnalyzer.java:112)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:107)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:126)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:126)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:126)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.doVisit(ProjectTypeContainer.java:126)
	at org.eclipse.pde.api.tools.internal.model.ProjectTypeContainer.accept(ProjectTypeContainer.java:62)
	at org.eclipse.pde.api.tools.internal.model.AbstractApiTypeContainer.accept(AbstractApiTypeContainer.java:60)
	at org.eclipse.pde.api.tools.internal.model.Component.accept(Component.java:66)
	at org.eclipse.pde.api.tools.internal.builder.ReferenceAnalyzer.extractReferences(ReferenceAnalyzer.java:210)
	at org.eclipse.pde.api.tools.internal.builder.ReferenceAnalyzer.analyze(ReferenceAnalyzer.java:243)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.checkApiUsage(BaseApiAnalyzer.java:1291)
	at org.eclipse.pde.api.tools.internal.builder.BaseApiAnalyzer.analyzeComponent(BaseApiAnalyzer.java:288)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.buildAll(ApiAnalysisBuilder.java:932)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.work(ApiAnalysisBuilder.java:416)
	at org.eclipse.pde.api.tools.internal.builder.ApiAnalysisBuilder.build(ApiAnalysisBuilder.java:396)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
eclipse.buildId=4.29.0.20230831-1210
java.version=20.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product -data C:\Users\jkubitz\jdt-master2023-09-05\ws
```

**Comment by jukzi** [comment]
@laeubi ok, then we just close this ticket - it's a rare case anyway, thanks for feedback
