### ISSUE TITLE
P2Tests.testBug242346 fails I20230919-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#748]
https://download.eclipse.org/eclipse/downloads/drops4/I20230919-1800/testresults/html/org.eclipse.pde.build.tests_ep430I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
/home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20230919-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230913-0815/scripts/genericTargets.xml:240: A problem occured while invoking the director.
at org.eclipse.equinox.p2.director.app.ant.DirectorTask.execute(DirectorTask.java:97)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:716)
at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:573)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.ant.core.AntRunner.run(AntRunner.java:506)
at org.eclipse.pde.build.tests.PDETestCase.runAntScript(PDETestCase.java:179)
at org.eclipse.pde.build.tests.PDETestCase.runAntScript(PDETestCase.java:171)
at org.eclipse.pde.build.internal.tests.p2.P2Tests.testBug242346(P2Tests.java:269)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by akurtakov** [comment]
Most likely fixed by https://github.com/eclipse-equinox/p2/commit/66c6f6adffad35e7d6f94c3e50e1b5e4a00bddaf . Will check tomorrow I-build.

**Comment by akurtakov** [comment]
Fixed in https://download.eclipse.org/eclipse/downloads/drops4/I20230920-1800/testResults.php
