### ISSUE TITLE
Target fails to load with NPE

### ISSUE THREAD

**Issue by mfvalenta** [eclipse-pde/eclipse.pde#751]
I tried Eclipse 4.29 with the project I work on and I got the following NPE when trying to load our target. This makes it impossible for us to use Eclipse 4.29

java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "this.fId" is null
	at org.eclipse.pde.core.target.NameVersionDescriptor.hashCode(NameVersionDescriptor.java:92)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.HashMap.containsKey(HashMap.java:594)
	at java.base/java.util.HashSet.contains(HashSet.java:205)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.cacheFeatures(IUBundleContainer.java:266)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.synchronizerChanged(IUBundleContainer.java:371)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.notify(P2TargetUtils.java:880)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:835)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:404)
	at org.eclipse.pde.core.target.LoadTargetDefinitionJob.runInWorkspace(LoadTargetDefinitionJob.java:123)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by mfvalenta** [comment]
It is worth noting that issue #507 was a previous issue we had loading targets.

**Comment by HannesWell** [comment]
It seems that you have a Feature in your TP that does not have an id, which is not valid.
Can you tell how this happens?
Of course this could be handled more gracefully by PDE, either by just ignoring such feature or showing a warning in the target.
But actually such Feature should never be build and published.

**Comment by mfvalenta** [comment]
I did a quick patch so I could proceed and logged the feature with the issue. It has an id and is built with no problem using Tycho. I suspect there is something in the feature.xml file that is causing a parsing error. I noticed there was XML parser changes in 4.29 so I suspect it is related to that. I'll try and find the time to diagnose the issue further in the next week or 2. 

Looking at the file again, I see it has the following as the first 2 lines. Maybe the DOCTYPE is the issue.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

**Comment by merks** [comment]
Can you share an example that reproduces the problem? It can never be fixed without that.

**Comment by mfvalenta** [comment]
Unfortunately, our targets are complicated and large and behind a firewall. As was mentioned in a previous comment, the issue is that a feature.xml in our target contains a <!DOCTYPE xml> which causes the xml parsing to fail to find the id.

I have managed to work around the issue by modifying the code to skip any features that do not have an id (see below). This seems to be adequate.

		List<TargetFeature> result = new ArrayList<>();
		for (TargetFeature allFeature : allFeatures) {
			**if (allFeature.getId() != null) {**
				NameVersionDescriptor candidate = new NameVersionDescriptor(allFeature.getId(), allFeature.getVersion(), NameVersionDescriptor.TYPE_FEATURE);
				if (features.contains(candidate)) {
					result.add(allFeature);
				}
			**}**
		}

**Comment by laeubi** [comment]
A feature without an ID is actually invalid, so why do you include it at all?

**Comment by mfvalenta** [comment]
The feature has an id. The issue is that PDE fails to parse the feature.xml. The likely reason for this is the presence of a DOCTYPE tag. I said this in my previous comment but it looks like the UI excluded the text due to the gt and lt. I've edited the comment. Fixing the target may be possible but is not really practical due to our organizational structure and the size and makeup of the target.

**Comment by laeubi** [comment]
> The issue is that PDE fails to parse the feature.xml.

If the feature can not be parsed then it is an invalid `feature.xml` ... of course it is not "nice" to fail with NPE here, but simply ignoring invalid features seems wrong as well.

**Comment by laeubi** [comment]
> I have managed to work around the issue by modifying the code to skip any features that do not have an id (see below). This seems to be adequate.

Please provide the patch as a PR that would make it much easier to review and possibly merge this.

**Comment by mfvalenta** [comment]
Are there a set of steps available to that describe the process of providing a PR? I haven't provided any updates to Eclipse since I was on the Eclipse Team team 2 decades ago and we self-host on our own Team provider so I am not familiar with the Eclipse git process.

**Comment by alxflam-work** [comment]
I've stumbled upon the same issue with some third-party features that i need to include in my target. The problem is that the root cause is not obvious to identify, as in `AbstractFeatureModel#load` the `SAXException` is neither logged nor rethrown but silently swallowed https://github.com/eclipse-pde/eclipse.pde/blob/1eacb118ad50267a2033dc989ffc8f5e8714f222/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/feature/AbstractFeatureModel.java#L97

If it would be printed as an error to the log with the path of the feature XML we'd have a useful error. The SAXException is: `::::2:10:-1:DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl`.

As there is no way to adjust this behavior by some configuration, the two workarounds available are:
- modify the pde.core code as @mfvalenta did
- or remove the DOCTYPEs from the feature.xmls

**Comment by merks** [comment]
Contribution instructions are here:

https://github.com/eclipse-pde/.github/blob/main/CONTRIBUTING.md

At the very least that exception should be logged so that one knows to remove doctypes...
