### ISSUE TITLE
IllegalStateException logged after creating new API baseline

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#767]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1115

```
java.lang.IllegalStateException: beginTask should only be called once per instance. At least call done() before further invocations
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:148)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.pde.api.tools.internal.model.ApiModelFactory.addComponents(ApiModelFactory.java:247)
	at org.eclipse.pde.api.tools.ui.internal.wizards.DirectoryBasedApiBaselineWizardPage$ReloadOperation.run(DirectoryBasedApiBaselineWizardPage.java:90)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalStateException: beginTask(Reading API Baseline..., 10) was called here previously
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:155)
	at org.eclipse.pde.api.tools.ui.internal.wizards.DirectoryBasedApiBaselineWizardPage$ReloadOperation.run(DirectoryBasedApiBaselineWizardPage.java:87)
	... 1 more
```

**Comment by opcoach** [comment]
Could not reproduce it in 2024-09. 
What was your configuration ?
