### ISSUE TITLE
TargetContentsGroup, TargetPlatformPreferencePage: Widget is disposed

### ISSUE THREAD

**Issue by jukzi** [eclipse-pde/eclipse.pde#813]
After adding a maven bundle to target platform i got:
```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Button.setSelection(Button.java:947)
	at org.eclipse.pde.internal.ui.shared.target.TargetContentsGroup.setInput(TargetContentsGroup.java:944)
	at org.eclipse.pde.internal.ui.wizards.target.TargetDefinitionContentPage.lambda$1(TargetDefinitionContentPage.java:255)
	at org.eclipse.pde.internal.ui.shared.target.TargetLocationsGroup.contentsChanged(TargetLocationsGroup.java:596)
	at org.eclipse.pde.internal.ui.shared.target.TargetLocationsGroup.handleEdit(TargetLocationsGroup.java:445)
	at org.eclipse.pde.internal.ui.shared.target.TargetLocationsGroup.lambda$3(TargetLocationsGroup.java:372)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
...
```

and

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Table.getItems(Table.java:2609)
	at org.eclipse.jface.viewers.CheckboxTableViewer.preservingSelection(CheckboxTableViewer.java:327)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1491)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:538)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1452)
	at org.eclipse.pde.internal.ui.preferences.TargetPlatformPreferencePage.handleEdit(TargetPlatformPreferencePage.java:703)
	at org.eclipse.pde.internal.ui.preferences.TargetPlatformPreferencePage.lambda$5(TargetPlatformPreferencePage.java:540)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)

```

**Comment by jukzi** [comment]
My be because i tried to open the link to "maven configuration" - which is not working (because preferences dialog is open in the background)
![image](https://github.com/eclipse-pde/eclipse.pde/assets/51790620/a291db29-66a4-470e-838f-476925a70403)
