### ISSUE TITLE
Failure of AttributeValueCompletionTests.testAttributeNameSuggestions

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-pde/eclipse.pde#844]
Happened in https://github.com/eclipse-pde/eclipse.pde/actions/runs/6693681585/job/18185349473#step:7:6738

```java
org.eclipse.pde.genericeditor.extension.tests.AttributeValueCompletionTests.testAttributeNameSuggestions -- Time elapsed: 0.192 s <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.pde.genericeditor.extension.tests.AttributeValueCompletionTests.testAttributeNameSuggestions(AttributeValueCompletionTests.java:30)
```

**Comment by fedejeanne** [comment]
Could someone with enough permissions please add the "help wanted" and "test" tags here? I'm working on some other stuff right now so I won't be able to work on this any time soon.
Thank you.

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.
