### ISSUE TITLE
NoSuchElementException being thrown when showing old launch configs

### ISSUE THREAD

**Issue by martinlippert** [eclipse-pde/eclipse.pde#88]
I am trying to open and edit old launch configs with the latest Eclipse 4.24 M2 bits and pieces, but I am getting this exception and it looks like the selection of plugins on the "Plug-ins" tab is gone (the list is full of un-checked plugins), so there is some data getting lost here.

```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getSelectedModels(BundleLauncherHelper.java:435)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getBundleMap(BundleLauncherHelper.java:417)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getWorkspaceBundleMap(BundleLauncherHelper.java:380)
	at org.eclipse.pde.internal.launching.launcher.BundleLauncherHelper.getAllSelectedPluginBundles(BundleLauncherHelper.java:107)
	at org.eclipse.pde.internal.ui.launcher.PluginBlock.initializePluginsState(PluginBlock.java:91)
	at org.eclipse.pde.internal.ui.launcher.PluginBlock.initializeFrom(PluginBlock.java:61)
	at org.eclipse.pde.internal.ui.launcher.BlockAdapter.initializeFrom(BlockAdapter.java:66)
	at org.eclipse.pde.ui.launcher.PluginsTab.initializeFrom(PluginsTab.java:158)
	at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfigurationTabGroup.lambda$0(AbstractPDELaunchConfigurationTabGroup.java:63)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.pde.ui.launcher.AbstractPDELaunchConfigurationTabGroup.initializeFrom(AbstractPDELaunchConfigurationTabGroup.java:55)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:182)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:868)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.lambda$4(LaunchConfigurationTabGroupViewer.java:728)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:743)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:675)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:655)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:1049)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.lambda$1(LaunchConfigurationsDialog.java:612)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1191)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:284)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:438)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4349)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3972)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1238)
	at org.eclipse.debug.ui.DebugUITools.lambda$1(DebugUITools.java:630)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:636)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:574)
	at org.eclipse.debug.ui.actions.OpenLaunchDialogAction.run(OpenLaunchDialogAction.java:85)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4608)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4394)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3970)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

This is moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=579872

**Comment by martinlippert** [comment]
If there is anything that I can provide to make the investigation of this easier. let me know. Since the data loss here is quite dramatic for someone working on plugin projects and having a bunch of launch configs with a specific set of plugins selected from the target platform and the workspace plugin project.

**Comment by vik-chand** [comment]
@HannesWell  Can you please have a look?

**Comment by iloveeclipse** [comment]
Why do we want `orElseThrow()` at all? If I understand it right, we should simply return empty iterator
https://github.com/eclipse-pde/eclipse.pde/blob/7eb3eab3467c8df9871b7b1144a332480cfae03e/ui/org.eclipse.pde.launching/src/org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.java#L435

**Comment by HannesWell** [comment]
Yes, I can take of this on thursday.And Andrey ist right, orElseThrow() should not be used here. An empty iterator could be returned if the Optional is empty, but I think the simplest way is to use ***@***.*** could you please check if the old launch-config contains workspace-plugins that are absent or closed? And If removing the absent/closed entries avoids the exception.

**Comment by HannesWell** [comment]
Looks like Github as detected the interesting part of my reply send via mail as an E-Mail an obfuscated it. I have edited it.

PR 93 should fix the problem. Feel free to have a look.
It also adds a test-case that should reproduce your problem and fails without the fix and passes with it.

**Comment by martinlippert** [comment]
> Yes, I can take of this on thursday.And Andrey ist right, orElseThrow() should not be used here. An empty iterator could be returned if the Optional is empty, but I think the simplest way is to use Optional.stream(). @martinlippert could you please check if the old launch-config contains workspace-plugins that are absent or closed? And If removing the absent/closed entries avoids the exception.

Yes, I checked this again and you can easily reproduce this error using these steps:

- open Eclipse with empty workspace
- import a plugin project
- create a launch config where this plugin from the workspace is selected (so switch to the mode where you select individual plugins)
- close the launch config dialog
- delete the plugin project from the workspace
- open the launch config again, it will immediately throw the exception

Many thanks @HannesWell for taking a look and implementing a fix for this. Very much appreciated!!!

**Comment by HannesWell** [comment]
Verified with Eclipse SDK

Version: 2022-06 (4.24)
Build id: I20220516-1800

**Comment by martinlippert** [comment]
Tested my setting with the latest fixes, works all well again. Many many thanks again @HannesWell !!!

**Comment by HannesWell** [comment]
Great. :)
You are welcome and thanks for the bug report.
