### ISSUE TITLE
New PDE test fails since I20231105-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#884]
We have new 8 P2Tests failures since I20231105-1800 build on all platforms.

* https://download.eclipse.org/eclipse/downloads/drops4/I20231105-1800/testResults.php
* https://download.eclipse.org/eclipse/downloads/drops4/I20231105-0400/testresults/html/org.eclipse.pde.build.tests_ep430I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230927-0753/scripts/build.xml:132: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230927-0753/templates/headless-build/customTargets.xml:13: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230927-0753/scripts/productBuild/allElements.xml:23: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230927-0753/scripts/genericTargets.xml:198: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/package.org.eclipse.pde.build.container.feature.all.xml:26: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/package.org.eclipse.pde.build.container.feature.all.xml:15: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230927-0753/scripts/productBuild/allElements.xml:64: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/package.org.eclipse.pde.build.container.feature.linux.gtk.x86_64.xml:100: The following error occurred while executing this line: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/package.org.eclipse.pde.build.container.feature.linux.gtk.x86_64.xml:146: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/tmp/eclipse/plugins/org.eclipse.equinox.launcher_1.6.600.v20231012-1237 does not exist.
```

```
Caused by: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/package.org.eclipse.pde.build.container.feature.linux.gtk.x86_64.xml:146: /home/jenkins/agent/workspace/AutomatedTests/ep430I-unit-cen64-gtk3-java17/workarea/I20231105-0400/eclipse-testing/test-eclipse/eclipse/pdebuild_folder/pde.build/237662/tmp/eclipse/plugins/org.eclipse.equinox.launcher_1.6.600.v20231012-1237 does not exist.
at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:512)
at org.apache.tools.ant.types.ArchiveFileSet.getDirectoryScanner(ArchiveFileSet.java:314)
at org.apache.tools.ant.taskdefs.Zip.grabResources(Zip.java:1588)
at org.apache.tools.ant.taskdefs.Zip.getResourcesToAdd(Zip.java:1325)
at org.apache.tools.ant.taskdefs.Zip.getResourcesToAdd(Zip.java:1263)
at org.apache.tools.ant.taskdefs.Zip.executeMain(Zip.java:671)
at org.apache.tools.ant.taskdefs.Zip.execute(Zip.java:627)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
at jdk.internal.reflect.GeneratedMethodAccessor493.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
at org.eclipse.ant.internal.core.ant.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:32)
at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
... 134 more
```

**Comment by iloveeclipse** [comment]
@HannesWell, @merks : probably related to recent p2 changes?

**Comment by merks** [comment]
Perhaps related to all the attribute removals and product definition changes, i.e., fragment recognition which might be more important to the PDE build than it was elsewhere.   I can't really make much sense of these tests, which also fail for me locally, though differently...

**Comment by iloveeclipse** [comment]
The ant fails at `<zipfileset dir="${eclipse.base}/plugins/org.eclipse.equinox.launcher_1.6.600.v20231012-1237" prefix="${pluginArchivePrefix}/org.eclipse.equinox.launcher_1.6.600.v20231012-1237"			/>` line
from
```
	<target name="assemble.archive">
		<antcall target="customAssembly">
			<param name="rootFolder" value="${eclipse.base}/linux.gtk.x86_64/${collectingFolder}"/>
			<param name="customTarget" value="pre.archive"/>
		</antcall>
		<zip destfile="${archiveFullPath}" filesonly="false" whenempty="skip" update="true">
			<zipfileset dir="${eclipse.base}/plugins/org.eclipse.equinox.launcher_1.6.600.v20231012-1237" prefix="${pluginArchivePrefix}/org.eclipse.equinox.launcher_1.6.600.v20231012-1237"			/>
			<zipfileset dir="${eclipse.base}/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.800.v20231003-1442" prefix="${pluginArchivePrefix}/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.800.v20231003-1442"			/>
			<zipfileset file="${eclipse.base}/plugins/org.eclipse.osgi_3.18.600.v20231025-1615.jar" fullpath="${pluginArchivePrefix}/org.eclipse.osgi_3.18.600.v20231025-1615.jar"			/>
			<zipfileset file="${eclipse.base}/plugins/org.eclipse.core.runtime_3.30.0.v20231102-0719.jar" fullpath="${pluginArchivePrefix}/org.eclipse.core.runtime_3.30.0.v20231102-0719.jar"			/>
			<zipfileset file="${eclipse.base}/plugins/org.eclipse.equinox.simpleconfigurator_1.5.0.v20230919-1457.jar" fullpath="${pluginArchivePrefix}/org.eclipse.equinox.simpleconfigurator_1.5.0.v20230919-1457.jar"			/>
			<zipfileset file="${eclipse.base}/plugins/org.eclipse.equinox.preferences_3.10.400.v20231102-2218.jar" fullpath="${pluginArchivePrefix}/org.eclipse.equinox.preferences_3.10.400.v20231102-2218.jar"			/>
		</zip>
	</target>
```

There is no directory with `org.eclipse.equinox.launcher_1.6.600.v20231012-1237` name at file system, but the jar file:

![image](https://github.com/eclipse-pde/eclipse.pde/assets/964108/1acc69a9-1f5e-4f8a-9f42-2aa72a6449ea)

I assume it is related to this code below (bug? failing assumptions?) together with recent changes how we package/install bundles:
* org.eclipse.pde.internal.build.AssembleConfigScriptGenerator.generateZipTarget()
* org.eclipse.pde.internal.build.ShapeAdvisor.getFinalShape(BundleDescription)

**Comment by iloveeclipse** [comment]
I have a fix, will push a PR in a moment. It is in `org.eclipse.pde.internal.build.ShapeAdvisor.getUnpackClause(BundleDescription)`

**Comment by iloveeclipse** [comment]
The code in question is an assumption from Eclipse 3.5 / bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=252246 / commit 4b3dff88acc2cbd93760c71e93454345f0a35380

**Comment by iloveeclipse** [comment]
PDE fails now as features **do not explicitly** specify "upack" attribute, so default "true" was assumed by PDE...

**Comment by merks** [comment]
You're awesome.  🏅

**Comment by iloveeclipse** [comment]
Note, the "old" fails are fixed but replaced now by "new" fails.

https://download.eclipse.org/eclipse/downloads/drops4/I20231107-1800/testresults/html/org.eclipse.pde.build.tests_ep430I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

This is most likely due hardcoded assumptions in tests that bundles should be unpacked by default (even if bundle shape is not explicitly specified as "dir").

I'm not sure I will have time today to check that & fix tests, so if anyone has time to do so today, help is welcome.

**Comment by laeubi** [comment]
Just wanted to make sure:

1. Title say `P2` test are failing but the link seems to indicate that `pde-build` test fails?
2. Does this imply that these tests are actually not executed as part of the verification builds?

**Comment by iloveeclipse** [comment]
For 1) see my previous comment. For 2): probably yes, haven't checked, I believe many pde tests are not executed in jenkins as the test setup is a bit more complex and no one managed to make tycho / maven / jenkins happy.

**Comment by iloveeclipse** [comment]
Fix for tests: https://github.com/eclipse-pde/eclipse.pde/pull/908.

**Comment by iloveeclipse** [comment]
Last test failing is `org.eclipse.pde.build.internal.tests.ScriptGenerationTests	testBug156043`.
I will try to fix itlater today.
