### ISSUE TITLE
NPE during find unused dependencies in the MANIFEST.MF editor 

### ISSUE THREAD

**Issue by vogella** [eclipse-pde/eclipse.pde#930]
Pressing the Find unused dependencies on certain plug-ins result in the following NPE

![image](https://github.com/eclipse-pde/eclipse.pde/assets/139910/eb78b6be-13b7-45ee-ab9b-6fd0b1476e45)

java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getExports()" because "this.module" is null
	at org.eclipse.jdt.internal.core.search.matching.ModularClassFileMatchLocator.matchPackageReferences(ModularClassFileMatchLocator.java:159)
	at org.eclipse.jdt.internal.core.search.matching.ModularClassFileMatchLocator.locateMatches(ModularClassFileMatchLocator.java:52)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2014)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1550)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.pde.internal.ui.search.dependencies.GatherUnusedDependenciesOperation.provideJavaClasses(GatherUnusedDependenciesOperation.java:206)
	at org.eclipse.pde.internal.ui.search.dependencies.GatherUnusedDependenciesOperation.isUnused(GatherUnusedDependenciesOperation.java:176)
	at org.eclipse.pde.internal.ui.search.dependencies.GatherUnusedDependenciesOperation.run(GatherUnusedDependenciesOperation.java:121)
	at org.eclipse.pde.internal.ui.search.dependencies.UnusedDependenciesJob.run(UnusedDependenciesJob.java:41)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by iloveeclipse** [comment]
> Pressing the Find unused dependencies on **certain plug-ins**

Please provide steps to reproduce.

**Comment by Dinesh0723** [comment]
The issue is not reproducible in Eclipse IDE, version: 2023-06 (4.28.0). Please let me know the eclipse version in which you are testing?
