### ISSUE TITLE
Unable to create PDE workspace via Oomph Setup

### ISSUE THREAD

**Issue by ptziegler** [eclipse-pde/eclipse.pde#956]
I just tried to set up a fresh PDE workspace again, which fails with the following error:

```
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1701363386383
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: PDE UI 3.15.0.v20231118-2008 (org.eclipse.pde.ui 3.15.0.v20231118-2008) requires 'java.package; biz.aQute.resolve [9.0.0,10.0.0)' but it could not be found
    ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
      ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1701363386383
      ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.pde.ui 0.0.0
```

From what I can tell, 677b79e4882f0537ae4b9b5e558c34b7fea455b1 introduced a dependency to [biz.aqute.resolve](https://mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.resolve), which is not part of the [Orbit](https://download.eclipse.org/tools/orbit/downloads/latest-R) repository, Oomph uses to resolve the modular targlet :/

**Comment by vogella** [comment]
cc @merks

**Comment by merks** [comment]
Yes only if the platform aggregator project is checked out is the  target platform it defines available and used. The next ibuild should contain it and also fix the problem.  Also normally orbit would regenerate to include what is in the platform’s tp but during this final quiet period for simrel I won’t update any orbit repos.  

So it’s bad timing and if you want instant gratification you must include the aggregator project setup.

**Comment by ptziegler** [comment]
That worked! Thank for the explanation.

**Comment by merks** [comment]
For me this transition period of platform opens during rc2 week is really a challenge. Things won’t be in proper shape until next Wednesday.  And I have to travel that day. 😱
